/* Generated by INTECRIO */
/* (c) 2014 ETAS (ETAS GmbH) */

/* System internal declarations and definitions - not intended for user purposes. */

#include "../a_basdef.h"
#include "../a_targma.h"

#include "OSC_Dyn.h"

/**** forward declaration of initialization functions ****/



/**** application modes ****/
/* important: differences to ES113X */

extern AppModeType etasStartupAppMode;
extern AppModeType etasInactiveAppMode;
extern AppModeType TimersAppMode;

T_appModeTableEntry appModeEntries[] =
{
    {(AppModeType *)&etasStartupAppMode, "etasStartup"},
    {(AppModeType *)&etasInactiveAppMode, "etasInactive"},
    {(AppModeType *)&TimersAppMode, "Timers"}
};

T_appModeTable appModeTable =
{
    1+2,    /* number of modes in appModeEntries */
    0+2,    /* index of default application mode */
    &appModeEntries[0]
};

/**** task referencing ****/

T_taskTableEntry taskTableEntries[] =
{
    {(TaskType *)&etasConfigTask, "etasConfigTask", TASK_MONITOR_PTR(etasConfigTask)},
    {(TaskType *)&SWT_CAN1_AP_BMS_AIRs_State, "SWT_CAN1_AP_BMS_AIRs_State", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_AIRs_State)},
    {(TaskType *)&SWT_CAN1_AP_BMS_BatteryTemperatures, "SWT_CAN1_AP_BMS_BatteryTemperatures", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_BatteryTemperatures)},
    {(TaskType *)&SWT_CAN1_AP_BMS_ChargerParameters, "SWT_CAN1_AP_BMS_ChargerParameters", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_ChargerParameters)},
    {(TaskType *)&SWT_CAN1_AP_BMS_SDC, "SWT_CAN1_AP_BMS_SDC", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_SDC)},
    {(TaskType *)&SWT_CAN1_AP_BMS_StateAndFailReport, "SWT_CAN1_AP_BMS_StateAndFailReport", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_StateAndFailReport)},
    {(TaskType *)&SWT_CAN1_AP_BMS_Voltages, "SWT_CAN1_AP_BMS_Voltages", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_Voltages)},
    {(TaskType *)&SWT_CAN1_AP_CurrentSensor, "SWT_CAN1_AP_CurrentSensor", TASK_MONITOR_PTR(SWT_CAN1_AP_CurrentSensor)},
    {(TaskType *)&SWT_CAN1_AP_DASH_Cooling, "SWT_CAN1_AP_DASH_Cooling", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_Cooling)},
    {(TaskType *)&SWT_CAN1_AP_DASH_CustomMode, "SWT_CAN1_AP_DASH_CustomMode", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_CustomMode)},
    {(TaskType *)&SWT_CAN1_AP_DASH_EnableDrive, "SWT_CAN1_AP_DASH_EnableDrive", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_EnableDrive)},
    {(TaskType *)&SWT_CAN1_AP_DASH_Mode, "SWT_CAN1_AP_DASH_Mode", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_Mode)},
    {(TaskType *)&SWT_CAN1_AP_DASH_PrechargeRequest, "SWT_CAN1_AP_DASH_PrechargeRequest", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_PrechargeRequest)},
    {(TaskType *)&SWT_CAN1_AP_DASH_TorqueLockOn, "SWT_CAN1_AP_DASH_TorqueLockOn", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_TorqueLockOn)},
    {(TaskType *)&SWT_CAN1_AP_Inverter_L_Tx, "SWT_CAN1_AP_Inverter_L_Tx", TASK_MONITOR_PTR(SWT_CAN1_AP_Inverter_L_Tx)},
    {(TaskType *)&SWT_CAN1_AP_Inverter_R_Tx, "SWT_CAN1_AP_Inverter_R_Tx", TASK_MONITOR_PTR(SWT_CAN1_AP_Inverter_R_Tx)},
    {(TaskType *)&SWT_CAN1_NM_BMS_Keep_Alive, "SWT_CAN1_NM_BMS_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN1_NM_BMS_Keep_Alive)},
    {(TaskType *)&SWT_CAN1_NM_DASH_Keep_Alive, "SWT_CAN1_NM_DASH_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN1_NM_DASH_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_EKF_EULER, "SWT_CAN2_AP_ELLIPSE_EKF_EULER", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_EKF_EULER)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_EKF_POS, "SWT_CAN2_AP_ELLIPSE_EKF_POS", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_EKF_POS)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_EKF_VEL, "SWT_CAN2_AP_ELLIPSE_EKF_VEL", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_EKF_VEL)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_IMU_ACCEL, "SWT_CAN2_AP_ELLIPSE_IMU_ACCEL", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_IMU_ACCEL)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_IMU_GYRO, "SWT_CAN2_AP_ELLIPSE_IMU_GYRO", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_IMU_GYRO)},
    {(TaskType *)&SWT_CAN2_AP_ELLIPSE_SLIP_CURV, "SWT_CAN2_AP_ELLIPSE_SLIP_CURV", TASK_MONITOR_PTR(SWT_CAN2_AP_ELLIPSE_SLIP_CURV)},
    {(TaskType *)&SWT_CAN2_AP_FECU_Data1, "SWT_CAN2_AP_FECU_Data1", TASK_MONITOR_PTR(SWT_CAN2_AP_FECU_Data1)},
    {(TaskType *)&SWT_CAN2_AP_FECU_Data2, "SWT_CAN2_AP_FECU_Data2", TASK_MONITOR_PTR(SWT_CAN2_AP_FECU_Data2)},
    {(TaskType *)&SWT_CAN2_AP_RECU_Data, "SWT_CAN2_AP_RECU_Data", TASK_MONITOR_PTR(SWT_CAN2_AP_RECU_Data)},
    {(TaskType *)&SWT_CAN2_MEAS_FECU_SDC, "SWT_CAN2_MEAS_FECU_SDC", TASK_MONITOR_PTR(SWT_CAN2_MEAS_FECU_SDC)},
    {(TaskType *)&SWT_CAN2_MEAS_RECU_SDC, "SWT_CAN2_MEAS_RECU_SDC", TASK_MONITOR_PTR(SWT_CAN2_MEAS_RECU_SDC)},
    {(TaskType *)&SWT_CAN2_NM_ELLIPSE_Status, "SWT_CAN2_NM_ELLIPSE_Status", TASK_MONITOR_PTR(SWT_CAN2_NM_ELLIPSE_Status)},
    {(TaskType *)&SWT_CAN2_NM_FECU_Keep_Alive, "SWT_CAN2_NM_FECU_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_FECU_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_NM_RECU_Keep_Alive, "SWT_CAN2_NM_RECU_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_RECU_Keep_Alive)},
    {(TaskType *)&Sync_25ms, "Sync_25ms", TASK_MONITOR_PTR(Sync_25ms)},
    {(TaskType *)&Timer_1000ms, "Timer_1000ms", TASK_MONITOR_PTR(Timer_1000ms)},
    {(TaskType *)&Timer_100ms, "Timer_100ms", TASK_MONITOR_PTR(Timer_100ms)},
    {(TaskType *)&Timer_25ms, "Timer_25ms", TASK_MONITOR_PTR(Timer_25ms)},
    {(TaskType *)&Timer_Inv, "Timer_Inv", TASK_MONITOR_PTR(Timer_Inv)}
};

T_taskTable taskTable =
{
    1 + 36,
    &taskTableEntries[0]
};

/************** init tasks ******************/
extern void crossbarHook_39_0(void);
extern void irt_Start_APPS_Implausibility(void);
extern void crossbarHook_39_1(void);
extern void crossbarHook_39_2(void);
extern void irt_Start_Sensors(void);
extern void crossbarHook_39_3(void);
extern void crossbarHook_39_4(void);
extern void irt_Start_Synchronism(void);
extern void crossbarHook_39_5(void);
extern void etasRtioInitProcess(void);
extern void rtioHook_39_0(void);
extern void etasRtioIntEnableProcess(void);

void etasStartupInitTask(void)
{
#ifdef STARTUP_INIT_TASK_START_FW_HOOK
    STARTUP_INIT_TASK_START_FW_HOOK
#endif
    
    etasInitModelProcess();
    etasInitOsProcess();



    etasRtioStartupProcess();


#ifdef STARTUP_INIT_TASK_END_FW_HOOK
    STARTUP_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void etasInactiveInitTask(void)
{
#ifdef INACTIVE_INIT_TASK_START_FW_HOOK
    INACTIVE_INIT_TASK_START_FW_HOOK
#endif

#ifdef INACTIVE_INIT_TASK_END_FW_HOOK
    INACTIVE_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void TimersInitTask(void)
{
#ifdef USER_APP_MODE_INIT_TASK_START_FW_HOOK
    USER_APP_MODE_INIT_TASK_START_FW_HOOK
#endif

    crossbarHook_39_0();
	irt_Start_APPS_Implausibility();
	crossbarHook_39_1();
	crossbarHook_39_2();
	irt_Start_Sensors();
	crossbarHook_39_3();
	crossbarHook_39_4();
	irt_Start_Synchronism();
	crossbarHook_39_5();
	etasRtioInitProcess();
	rtioHook_39_0();
	etasRtioIntEnableProcess();
	
    
#ifdef USER_APP_MODE_INIT_TASK_END_FW_HOOK
    USER_APP_MODE_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void etasInitTasks(void)
{
    AppModeType curAppMode;

    curAppMode = GetActiveApplicationMode();

    switch(curAppMode)
    {
        case etasStartup:
            etasStartupInitTask();
            break;

        case etasInactive:
            etasInactiveInitTask();
            break;

        case Timers:
            TimersInitTask();
            break;
    }

    return;
}

/**************** exit tasks *****************/
extern void crossbarHook_40_0(void);
extern void irt_Terminate_APPS_Implausibility(void);
extern void crossbarHook_40_1(void);
extern void crossbarHook_40_2(void);
extern void irt_Terminate_Sensors(void);
extern void crossbarHook_40_3(void);
extern void crossbarHook_40_4(void);
extern void irt_Terminate_Synchronism(void);
extern void crossbarHook_40_5(void);
extern void etasRtioIntDisableProcess(void);
extern void rtioHook_40_0(void);
extern void etasRtioExitProcess(void);

void etasStartupExitTask(void)
{
#ifdef STARTUP_EXIT_TASK_START_FW_HOOK
    STARTUP_EXIT_TASK_START_FW_HOOK
#endif

#ifdef STARTUP_EXIT_TASK_END_FW_HOOK
    STARTUP_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void etasInactiveExitTask(void)
{
#ifdef INACTIVE_EXIT_TASK_START_FW_HOOK
    INACTIVE_EXIT_TASK_START_FW_HOOK
#endif

#ifdef INACTIVE_EXIT_TASK_END_FW_HOOK
    INACTIVE_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void TimersExitTask(void)
{
#ifdef USER_APP_MODE_EXIT_TASK_START_FW_HOOK
    USER_APP_MODE_EXIT_TASK_START_FW_HOOK
#endif

    crossbarHook_40_0();
	irt_Terminate_APPS_Implausibility();
	crossbarHook_40_1();
	crossbarHook_40_2();
	irt_Terminate_Sensors();
	crossbarHook_40_3();
	crossbarHook_40_4();
	irt_Terminate_Synchronism();
	crossbarHook_40_5();
	etasRtioIntDisableProcess();
	rtioHook_40_0();
	etasRtioExitProcess();
	
    
#ifdef USER_APP_MODE_EXIT_TASK_END_FW_HOOK
    USER_APP_MODE_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void etasExitTasks(void)
{
    AppModeType curAppMode;

    curAppMode = GetActiveApplicationMode();

    switch(curAppMode)
    {
        case etasStartup:
            etasStartupExitTask();
            break;

        case etasInactive:
            etasInactiveExitTask();
            break;

        case Timers:
            TimersExitTask();
            break;
    }

    return;
}

/**** OS administration ****/

T_osAdmin osAdmin =
{
    &appModeTable,
    &taskTable
};

/************ dummies **********/

/* stimuligenerator table */
sgTaskTableEntry sgTaskTable[1 + 36 + 2] = {NULL}; /* all elements are initialized with 0 */


