/* Generated by INTECRIO */
/* (c) 2014 ETAS (ETAS GmbH) */

/* System internal declarations and definitions - not intended for user purposes. */

#include "../a_basdef.h"
#include "../a_targma.h"

#include "OSC_Dyn.h"

/**** forward declaration of initialization functions ****/



/**** application modes ****/
/* important: differences to ES113X */

extern AppModeType etasStartupAppMode;
extern AppModeType etasInactiveAppMode;
extern AppModeType TimersAppMode;

T_appModeTableEntry appModeEntries[] =
{
    {(AppModeType *)&etasStartupAppMode, "etasStartup"},
    {(AppModeType *)&etasInactiveAppMode, "etasInactive"},
    {(AppModeType *)&TimersAppMode, "Timers"}
};

T_appModeTable appModeTable =
{
    1+2,    /* number of modes in appModeEntries */
    0+2,    /* index of default application mode */
    &appModeEntries[0]
};

/**** task referencing ****/

T_taskTableEntry taskTableEntries[] =
{
    {(TaskType *)&etasConfigTask, "etasConfigTask", TASK_MONITOR_PTR(etasConfigTask)},
    {(TaskType *)&SWT_CAN1_AP_BMS_AIRs_State, "SWT_CAN1_AP_BMS_AIRs_State", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_AIRs_State)},
    {(TaskType *)&SWT_CAN1_AP_BMS_BatteryTemperatures, "SWT_CAN1_AP_BMS_BatteryTemperatures", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_BatteryTemperatures)},
    {(TaskType *)&SWT_CAN1_AP_BMS_ChargerParameters, "SWT_CAN1_AP_BMS_ChargerParameters", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_ChargerParameters)},
    {(TaskType *)&SWT_CAN1_AP_BMS_Current_SOC, "SWT_CAN1_AP_BMS_Current_SOC", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_Current_SOC)},
    {(TaskType *)&SWT_CAN1_AP_BMS_Current_SOC_SOH, "SWT_CAN1_AP_BMS_Current_SOC_SOH", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_Current_SOC_SOH)},
    {(TaskType *)&SWT_CAN1_AP_BMS_Current_SOC_SOH1, "SWT_CAN1_AP_BMS_Current_SOC_SOH1", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_Current_SOC_SOH1)},
    {(TaskType *)&SWT_CAN1_AP_BMS_OnBoardTemperatures, "SWT_CAN1_AP_BMS_OnBoardTemperatures", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_OnBoardTemperatures)},
    {(TaskType *)&SWT_CAN1_AP_BMS_OnBoardTemperatures1, "SWT_CAN1_AP_BMS_OnBoardTemperatures1", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_OnBoardTemperatures1)},
    {(TaskType *)&SWT_CAN1_AP_BMS_StateAndFailReport, "SWT_CAN1_AP_BMS_StateAndFailReport", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_StateAndFailReport)},
    {(TaskType *)&SWT_CAN1_AP_BMS_Voltages, "SWT_CAN1_AP_BMS_Voltages", TASK_MONITOR_PTR(SWT_CAN1_AP_BMS_Voltages)},
    {(TaskType *)&SWT_CAN1_AP_DASH_CustomMode, "SWT_CAN1_AP_DASH_CustomMode", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_CustomMode)},
    {(TaskType *)&SWT_CAN1_AP_DASH_EnableDrive, "SWT_CAN1_AP_DASH_EnableDrive", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_EnableDrive)},
    {(TaskType *)&SWT_CAN1_AP_DASH_Mode, "SWT_CAN1_AP_DASH_Mode", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_Mode)},
    {(TaskType *)&SWT_CAN1_AP_DASH_PrechargeRequest, "SWT_CAN1_AP_DASH_PrechargeRequest", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_PrechargeRequest)},
    {(TaskType *)&SWT_CAN1_AP_DASH_TorqueLockOn, "SWT_CAN1_AP_DASH_TorqueLockOn", TASK_MONITOR_PTR(SWT_CAN1_AP_DASH_TorqueLockOn)},
    {(TaskType *)&SWT_CAN1_AP_Inverter_L_Tx, "SWT_CAN1_AP_Inverter_L_Tx", TASK_MONITOR_PTR(SWT_CAN1_AP_Inverter_L_Tx)},
    {(TaskType *)&SWT_CAN1_AP_Inverter_R_Tx, "SWT_CAN1_AP_Inverter_R_Tx", TASK_MONITOR_PTR(SWT_CAN1_AP_Inverter_R_Tx)},
    {(TaskType *)&SWT_CAN1_AP_SHUTDOWN_State, "SWT_CAN1_AP_SHUTDOWN_State", TASK_MONITOR_PTR(SWT_CAN1_AP_SHUTDOWN_State)},
    {(TaskType *)&SWT_CAN1_NM_BMS_Keep_Alive, "SWT_CAN1_NM_BMS_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN1_NM_BMS_Keep_Alive)},
    {(TaskType *)&SWT_CAN1_NM_DASH_Keep_Alive, "SWT_CAN1_NM_DASH_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN1_NM_DASH_Keep_Alive)},
    {(TaskType *)&SWT_CAN1_NM_SHUTDOWN_Keep_Alive, "SWT_CAN1_NM_SHUTDOWN_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN1_NM_SHUTDOWN_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_AP_ACCEL_F_Data, "SWT_CAN2_AP_ACCEL_F_Data", TASK_MONITOR_PTR(SWT_CAN2_AP_ACCEL_F_Data)},
    {(TaskType *)&SWT_CAN2_AP_ACCEL_R_Data, "SWT_CAN2_AP_ACCEL_R_Data", TASK_MONITOR_PTR(SWT_CAN2_AP_ACCEL_R_Data)},
    {(TaskType *)&SWT_CAN2_AP_ACCEL_R_Data2, "SWT_CAN2_AP_ACCEL_R_Data2", TASK_MONITOR_PTR(SWT_CAN2_AP_ACCEL_R_Data2)},
    {(TaskType *)&SWT_CAN2_AP_ADCAN_Data1, "SWT_CAN2_AP_ADCAN_Data1", TASK_MONITOR_PTR(SWT_CAN2_AP_ADCAN_Data1)},
    {(TaskType *)&SWT_CAN2_AP_ADCAN_Data2, "SWT_CAN2_AP_ADCAN_Data2", TASK_MONITOR_PTR(SWT_CAN2_AP_ADCAN_Data2)},
    {(TaskType *)&SWT_CAN2_AP_ELIPSE_VelAngular, "SWT_CAN2_AP_ELIPSE_VelAngular", TASK_MONITOR_PTR(SWT_CAN2_AP_ELIPSE_VelAngular)},
    {(TaskType *)&SWT_CAN2_AP_ELIPSE_VelBody, "SWT_CAN2_AP_ELIPSE_VelBody", TASK_MONITOR_PTR(SWT_CAN2_AP_ELIPSE_VelBody)},
    {(TaskType *)&SWT_CAN2_AP_LV_Derivation_LVData, "SWT_CAN2_AP_LV_Derivation_LVData", TASK_MONITOR_PTR(SWT_CAN2_AP_LV_Derivation_LVData)},
    {(TaskType *)&SWT_CAN2_NM_ACCEL_F_Keep_Alive, "SWT_CAN2_NM_ACCEL_F_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_ACCEL_F_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_NM_ACCEL_R_Keep_Alive, "SWT_CAN2_NM_ACCEL_R_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_ACCEL_R_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_NM_ADCAN_Keep_Alive, "SWT_CAN2_NM_ADCAN_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_ADCAN_Keep_Alive)},
    {(TaskType *)&SWT_CAN2_NM_LV_Derivation_Keep_Alive, "SWT_CAN2_NM_LV_Derivation_Keep_Alive", TASK_MONITOR_PTR(SWT_CAN2_NM_LV_Derivation_Keep_Alive)},
    {(TaskType *)&Sync_25ms, "Sync_25ms", TASK_MONITOR_PTR(Sync_25ms)},
    {(TaskType *)&Timer_1000ms, "Timer_1000ms", TASK_MONITOR_PTR(Timer_1000ms)},
    {(TaskType *)&Timer_100ms, "Timer_100ms", TASK_MONITOR_PTR(Timer_100ms)},
    {(TaskType *)&Timer_25ms, "Timer_25ms", TASK_MONITOR_PTR(Timer_25ms)},
    {(TaskType *)&Timer_Inv, "Timer_Inv", TASK_MONITOR_PTR(Timer_Inv)}
};

T_taskTable taskTable =
{
    1 + 38,
    &taskTableEntries[0]
};

/************** init tasks ******************/
extern void crossbarHook_41_0(void);
extern void irt_Start_Accel_Data_ETR07(void);
extern void crossbarHook_41_1(void);
extern void crossbarHook_41_2(void);
extern void irt_Start_Car_State_ETR07(void);
extern void crossbarHook_41_3(void);
extern void crossbarHook_41_4(void);
extern void irt_Start_Disconnections_ETR07(void);
extern void crossbarHook_41_5(void);
extern void crossbarHook_41_6(void);
extern void irt_Start_inverters_action_ETR07(void);
extern void crossbarHook_41_7(void);
extern void crossbarHook_41_8(void);
extern void irt_Start_Inverters_Data_ETR07(void);
extern void crossbarHook_41_9(void);
extern void crossbarHook_41_10(void);
extern void irt_Start_Torque_Control_ETR07(void);
extern void crossbarHook_41_11(void);
extern void crossbarHook_41_12(void);
extern void irt_Start_Pedals_Susp_Sensors_ETR07(void);
extern void crossbarHook_41_13(void);
extern void crossbarHook_41_14(void);
extern void irt_Start_Racing_Mode_ETR07(void);
extern void crossbarHook_41_15(void);
extern void crossbarHook_41_16(void);
extern void irt_Start_Synchronism_ETR07(void);
extern void crossbarHook_41_17(void);
extern void etasRtioInitProcess(void);
extern void rtioHook_41_0(void);
extern void etasRtioIntEnableProcess(void);

void etasStartupInitTask(void)
{
#ifdef STARTUP_INIT_TASK_START_FW_HOOK
    STARTUP_INIT_TASK_START_FW_HOOK
#endif
    
    etasInitModelProcess();
    etasInitOsProcess();



    etasRtioStartupProcess();


#ifdef STARTUP_INIT_TASK_END_FW_HOOK
    STARTUP_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void etasInactiveInitTask(void)
{
#ifdef INACTIVE_INIT_TASK_START_FW_HOOK
    INACTIVE_INIT_TASK_START_FW_HOOK
#endif

#ifdef INACTIVE_INIT_TASK_END_FW_HOOK
    INACTIVE_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void TimersInitTask(void)
{
#ifdef USER_APP_MODE_INIT_TASK_START_FW_HOOK
    USER_APP_MODE_INIT_TASK_START_FW_HOOK
#endif

    crossbarHook_41_0();
	irt_Start_Accel_Data_ETR07();
	crossbarHook_41_1();
	crossbarHook_41_2();
	irt_Start_Car_State_ETR07();
	crossbarHook_41_3();
	crossbarHook_41_4();
	irt_Start_Disconnections_ETR07();
	crossbarHook_41_5();
	crossbarHook_41_6();
	irt_Start_inverters_action_ETR07();
	crossbarHook_41_7();
	crossbarHook_41_8();
	irt_Start_Inverters_Data_ETR07();
	crossbarHook_41_9();
	crossbarHook_41_10();
	irt_Start_Torque_Control_ETR07();
	crossbarHook_41_11();
	crossbarHook_41_12();
	irt_Start_Pedals_Susp_Sensors_ETR07();
	crossbarHook_41_13();
	crossbarHook_41_14();
	irt_Start_Racing_Mode_ETR07();
	crossbarHook_41_15();
	crossbarHook_41_16();
	irt_Start_Synchronism_ETR07();
	crossbarHook_41_17();
	etasRtioInitProcess();
	rtioHook_41_0();
	etasRtioIntEnableProcess();
	
    
#ifdef USER_APP_MODE_INIT_TASK_END_FW_HOOK
    USER_APP_MODE_INIT_TASK_END_FW_HOOK
#endif

    return;
}

void etasInitTasks(void)
{
    AppModeType curAppMode;

    curAppMode = GetActiveApplicationMode();

    switch(curAppMode)
    {
        case etasStartup:
            etasStartupInitTask();
            break;

        case etasInactive:
            etasInactiveInitTask();
            break;

        case Timers:
            TimersInitTask();
            break;
    }

    return;
}

/**************** exit tasks *****************/
extern void crossbarHook_42_0(void);
extern void irt_Terminate_Accel_Data_ETR07(void);
extern void crossbarHook_42_1(void);
extern void crossbarHook_42_2(void);
extern void irt_Terminate_Car_State_ETR07(void);
extern void crossbarHook_42_3(void);
extern void crossbarHook_42_4(void);
extern void irt_Terminate_inverters_action_ETR07(void);
extern void crossbarHook_42_5(void);
extern void crossbarHook_42_6(void);
extern void irt_Terminate_Disconnections_ETR07(void);
extern void crossbarHook_42_7(void);
extern void crossbarHook_42_8(void);
extern void irt_Terminate_Racing_Mode_ETR07(void);
extern void crossbarHook_42_9(void);
extern void crossbarHook_42_10(void);
extern void irt_Terminate_Torque_Control_ETR07(void);
extern void crossbarHook_42_11(void);
extern void crossbarHook_42_12(void);
extern void irt_Terminate_Pedals_Susp_Sensors_ETR07(void);
extern void crossbarHook_42_13(void);
extern void crossbarHook_42_14(void);
extern void irt_Terminate_Inverters_Data_ETR07(void);
extern void crossbarHook_42_15(void);
extern void crossbarHook_42_16(void);
extern void irt_Terminate_Synchronism_ETR07(void);
extern void crossbarHook_42_17(void);
extern void etasRtioIntDisableProcess(void);
extern void rtioHook_42_0(void);
extern void etasRtioExitProcess(void);

void etasStartupExitTask(void)
{
#ifdef STARTUP_EXIT_TASK_START_FW_HOOK
    STARTUP_EXIT_TASK_START_FW_HOOK
#endif

#ifdef STARTUP_EXIT_TASK_END_FW_HOOK
    STARTUP_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void etasInactiveExitTask(void)
{
#ifdef INACTIVE_EXIT_TASK_START_FW_HOOK
    INACTIVE_EXIT_TASK_START_FW_HOOK
#endif

#ifdef INACTIVE_EXIT_TASK_END_FW_HOOK
    INACTIVE_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void TimersExitTask(void)
{
#ifdef USER_APP_MODE_EXIT_TASK_START_FW_HOOK
    USER_APP_MODE_EXIT_TASK_START_FW_HOOK
#endif

    crossbarHook_42_0();
	irt_Terminate_Accel_Data_ETR07();
	crossbarHook_42_1();
	crossbarHook_42_2();
	irt_Terminate_Car_State_ETR07();
	crossbarHook_42_3();
	crossbarHook_42_4();
	irt_Terminate_inverters_action_ETR07();
	crossbarHook_42_5();
	crossbarHook_42_6();
	irt_Terminate_Disconnections_ETR07();
	crossbarHook_42_7();
	crossbarHook_42_8();
	irt_Terminate_Racing_Mode_ETR07();
	crossbarHook_42_9();
	crossbarHook_42_10();
	irt_Terminate_Torque_Control_ETR07();
	crossbarHook_42_11();
	crossbarHook_42_12();
	irt_Terminate_Pedals_Susp_Sensors_ETR07();
	crossbarHook_42_13();
	crossbarHook_42_14();
	irt_Terminate_Inverters_Data_ETR07();
	crossbarHook_42_15();
	crossbarHook_42_16();
	irt_Terminate_Synchronism_ETR07();
	crossbarHook_42_17();
	etasRtioIntDisableProcess();
	rtioHook_42_0();
	etasRtioExitProcess();
	
    
#ifdef USER_APP_MODE_EXIT_TASK_END_FW_HOOK
    USER_APP_MODE_EXIT_TASK_END_FW_HOOK
#endif
    return;
}

void etasExitTasks(void)
{
    AppModeType curAppMode;

    curAppMode = GetActiveApplicationMode();

    switch(curAppMode)
    {
        case etasStartup:
            etasStartupExitTask();
            break;

        case etasInactive:
            etasInactiveExitTask();
            break;

        case Timers:
            TimersExitTask();
            break;
    }

    return;
}

/**** OS administration ****/

T_osAdmin osAdmin =
{
    &appModeTable,
    &taskTable
};

/************ dummies **********/

/* stimuligenerator table */
sgTaskTableEntry sgTaskTable[1 + 38 + 2] = {NULL}; /* all elements are initialized with 0 */


