/* Generated by INTECRIO */
/* (c) 2014 ETAS (ETAS GmbH) */

/* System internal declarations - not intended for user purposes. */

#ifndef __RTA_INTERFACE_H
#define __RTA_INTERFACE_H

/* User application modes only */
extern AppModeType TimerAppMode;


#endif /* __RTA_INTERFACE_H */

