/* Generated by INTECRIO OS Configurator Plugin */
/* (c) 2004 ETAS (ETAS GmbH) */

#include "../a_basdef.h"

/*********** crossbar hooks ***************/

/* entries for crossbar task table */

/* crossbar hook in task 1 SWT_CAN1_AP_BMS_AIRs_State */
crossbarHookTableEntry crossbarHookTable1[1] = {NULL};

/* crossbar hook in task 2 SWT_CAN1_AP_BMS_BatteryTemperatures */
crossbarHookTableEntry crossbarHookTable2[1] = {NULL};

/* crossbar hook in task 3 SWT_CAN1_AP_BMS_ChargerParameters */
crossbarHookTableEntry crossbarHookTable3[1] = {NULL};

/* crossbar hook in task 4 SWT_CAN1_AP_BMS_Current_SOC_SOH */
crossbarHookTableEntry crossbarHookTable4[1] = {NULL};

/* crossbar hook in task 5 SWT_CAN1_AP_BMS_OnBoardTemperatures */
crossbarHookTableEntry crossbarHookTable5[1] = {NULL};

/* crossbar hook in task 6 SWT_CAN1_AP_BMS_StateAndFailReport */
crossbarHookTableEntry crossbarHookTable6[1] = {NULL};

/* crossbar hook in task 7 SWT_CAN1_AP_BMS_Voltages */
crossbarHookTableEntry crossbarHookTable7[1] = {NULL};

/* crossbar hook in task 8 SWT_CAN1_AP_DASH_CustomMode */
crossbarHookTableEntry crossbarHookTable8[1] = {NULL};

/* crossbar hook in task 9 SWT_CAN1_AP_DASH_EnableDrive */
crossbarHookTableEntry crossbarHookTable9[1] = {NULL};

/* crossbar hook in task 10 SWT_CAN1_AP_DASH_Mode */
crossbarHookTableEntry crossbarHookTable10[1] = {NULL};

/* crossbar hook in task 11 SWT_CAN1_AP_DASH_PrechargeRequest */
crossbarHookTableEntry crossbarHookTable11[1] = {NULL};

/* crossbar hook in task 12 SWT_CAN1_AP_DASH_TorqueLockOn */
crossbarHookTableEntry crossbarHookTable12[1] = {NULL};

/* crossbar hook in task 13 SWT_CAN1_AP_Inverter_L_Tx */
crossbarHookTableEntry crossbarHookTable13[1] = {NULL};

/* crossbar hook in task 14 SWT_CAN1_AP_Inverter_R_Tx */
crossbarHookTableEntry crossbarHookTable14[1] = {NULL};

/* crossbar hook in task 15 SWT_CAN1_AP_SHUTDOWN_State */
crossbarHookTableEntry crossbarHookTable15[1] = {NULL};

/* crossbar hook in task 16 SWT_CAN1_NM_BMS_Keep_Alive */
crossbarHookTableEntry crossbarHookTable16[1] = {NULL};

/* crossbar hook in task 17 SWT_CAN1_NM_DASH_Keep_Alive */
crossbarHookTableEntry crossbarHookTable17[1] = {NULL};

/* crossbar hook in task 18 SWT_CAN1_NM_SHUTDOWN_Keep_Alive */
crossbarHookTableEntry crossbarHookTable18[1] = {NULL};

/* crossbar hook in task 19 SWT_CAN2_AP_ACCEL_F_Data */
crossbarHookTableEntry crossbarHookTable19[1] = {NULL};

/* crossbar hook in task 20 SWT_CAN2_AP_ACCEL_R_Data */
crossbarHookTableEntry crossbarHookTable20[1] = {NULL};

/* crossbar hook in task 21 SWT_CAN2_AP_ACCEL_R_Data2 */
crossbarHookTableEntry crossbarHookTable21[1] = {NULL};

/* crossbar hook in task 22 SWT_CAN2_AP_ADCAN_Data1 */
crossbarHookTableEntry crossbarHookTable22[1] = {NULL};

/* crossbar hook in task 23 SWT_CAN2_AP_ADCAN_Data2 */
crossbarHookTableEntry crossbarHookTable23[1] = {NULL};

/* crossbar hook in task 24 SWT_CAN2_AP_ELLIPSE_EKF_EULER */
crossbarHookTableEntry crossbarHookTable24[1] = {NULL};

/* crossbar hook in task 25 SWT_CAN2_AP_ELLIPSE_EKF_POS */
crossbarHookTableEntry crossbarHookTable25[1] = {NULL};

/* crossbar hook in task 26 SWT_CAN2_AP_ELLIPSE_EKF_VEL_BODY */
crossbarHookTableEntry crossbarHookTable26[1] = {NULL};

/* crossbar hook in task 27 SWT_CAN2_AP_ELLIPSE_IMU_ACCEL */
crossbarHookTableEntry crossbarHookTable27[1] = {NULL};

/* crossbar hook in task 28 SWT_CAN2_AP_ELLIPSE_IMU_GYRO */
crossbarHookTableEntry crossbarHookTable28[1] = {NULL};

/* crossbar hook in task 29 SWT_CAN2_AP_ELLIPSE_MAG */
crossbarHookTableEntry crossbarHookTable29[1] = {NULL};

/* crossbar hook in task 30 SWT_CAN2_AP_ELLIPSE_SLIP_CURV */
crossbarHookTableEntry crossbarHookTable30[1] = {NULL};

/* crossbar hook in task 31 SWT_CAN2_AP_LV_Derivation_LVData */
crossbarHookTableEntry crossbarHookTable31[1] = {NULL};

/* crossbar hook in task 32 SWT_CAN2_NM_ACCEL_F_Keep_Alive */
crossbarHookTableEntry crossbarHookTable32[1] = {NULL};

/* crossbar hook in task 33 SWT_CAN2_NM_ACCEL_R_Keep_Alive */
crossbarHookTableEntry crossbarHookTable33[1] = {NULL};

/* crossbar hook in task 34 SWT_CAN2_NM_ADCAN_Keep_Alive */
crossbarHookTableEntry crossbarHookTable34[1] = {NULL};

/* crossbar hook in task 35 SWT_CAN2_NM_ELLIPSE_Status */
crossbarHookTableEntry crossbarHookTable35[1] = {NULL};

/* crossbar hook in task 36 SWT_CAN2_NM_LV_Derivation_Keep_Alive */
crossbarHookTableEntry crossbarHookTable36[1] = {NULL};

/* crossbar hook in task 37 Sync_25ms */
crossbarHookTableEntry crossbarHookTable37[4] = {NULL, NULL, NULL, NULL};

/* crossbar hook in task 38 Timer_1000ms */
crossbarHookTableEntry crossbarHookTable38[2] = {NULL, NULL};

/* crossbar hook in task 39 Timer_100ms */
crossbarHookTableEntry crossbarHookTable39[2] = {NULL, NULL};

/* crossbar hook in task 40 Timer_25ms */
crossbarHookTableEntry crossbarHookTable40[20] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 41 Timer_Inv */
crossbarHookTableEntry crossbarHookTable41[6] = {NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 42 ISR_CAN1 */
crossbarHookTableEntry crossbarHookTable42[1] = {NULL};

/* crossbar hook in task 43 ISR_CAN2 */
crossbarHookTableEntry crossbarHookTable43[1] = {NULL};

/* crossbar hook in task 44 Init */
crossbarHookTableEntry crossbarHookTable44[24] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 45 Exit */
crossbarHookTableEntry crossbarHookTable45[24] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};


/* crossbar task table */
crossbarTaskTableEntry crossbarTaskTable[46] =
{
	{NULL},
	{&crossbarHookTable1[0]},
	{&crossbarHookTable2[0]},
	{&crossbarHookTable3[0]},
	{&crossbarHookTable4[0]},
	{&crossbarHookTable5[0]},
	{&crossbarHookTable6[0]},
	{&crossbarHookTable7[0]},
	{&crossbarHookTable8[0]},
	{&crossbarHookTable9[0]},
	{&crossbarHookTable10[0]},
	{&crossbarHookTable11[0]},
	{&crossbarHookTable12[0]},
	{&crossbarHookTable13[0]},
	{&crossbarHookTable14[0]},
	{&crossbarHookTable15[0]},
	{&crossbarHookTable16[0]},
	{&crossbarHookTable17[0]},
	{&crossbarHookTable18[0]},
	{&crossbarHookTable19[0]},
	{&crossbarHookTable20[0]},
	{&crossbarHookTable21[0]},
	{&crossbarHookTable22[0]},
	{&crossbarHookTable23[0]},
	{&crossbarHookTable24[0]},
	{&crossbarHookTable25[0]},
	{&crossbarHookTable26[0]},
	{&crossbarHookTable27[0]},
	{&crossbarHookTable28[0]},
	{&crossbarHookTable29[0]},
	{&crossbarHookTable30[0]},
	{&crossbarHookTable31[0]},
	{&crossbarHookTable32[0]},
	{&crossbarHookTable33[0]},
	{&crossbarHookTable34[0]},
	{&crossbarHookTable35[0]},
	{&crossbarHookTable36[0]},
	{&crossbarHookTable37[0]},
	{&crossbarHookTable38[0]},
	{&crossbarHookTable39[0]},
	{&crossbarHookTable40[0]},
	{&crossbarHookTable41[0]},
	{&crossbarHookTable42[0]},
	{&crossbarHookTable43[0]},
	{&crossbarHookTable44[0]},
	{&crossbarHookTable45[0]}
};

/* crossbar hook processes */
void crossbarHook_1_0(void)
{
	crossbarHook(1,0);
	return;
}

void crossbarHook_2_0(void)
{
	crossbarHook(2,0);
	return;
}

void crossbarHook_3_0(void)
{
	crossbarHook(3,0);
	return;
}

void crossbarHook_4_0(void)
{
	crossbarHook(4,0);
	return;
}

void crossbarHook_5_0(void)
{
	crossbarHook(5,0);
	return;
}

void crossbarHook_6_0(void)
{
	crossbarHook(6,0);
	return;
}

void crossbarHook_7_0(void)
{
	crossbarHook(7,0);
	return;
}

void crossbarHook_8_0(void)
{
	crossbarHook(8,0);
	return;
}

void crossbarHook_9_0(void)
{
	crossbarHook(9,0);
	return;
}

void crossbarHook_10_0(void)
{
	crossbarHook(10,0);
	return;
}

void crossbarHook_11_0(void)
{
	crossbarHook(11,0);
	return;
}

void crossbarHook_12_0(void)
{
	crossbarHook(12,0);
	return;
}

void crossbarHook_13_0(void)
{
	crossbarHook(13,0);
	return;
}

void crossbarHook_14_0(void)
{
	crossbarHook(14,0);
	return;
}

void crossbarHook_15_0(void)
{
	crossbarHook(15,0);
	return;
}

void crossbarHook_16_0(void)
{
	crossbarHook(16,0);
	return;
}

void crossbarHook_17_0(void)
{
	crossbarHook(17,0);
	return;
}

void crossbarHook_18_0(void)
{
	crossbarHook(18,0);
	return;
}

void crossbarHook_19_0(void)
{
	crossbarHook(19,0);
	return;
}

void crossbarHook_20_0(void)
{
	crossbarHook(20,0);
	return;
}

void crossbarHook_21_0(void)
{
	crossbarHook(21,0);
	return;
}

void crossbarHook_22_0(void)
{
	crossbarHook(22,0);
	return;
}

void crossbarHook_23_0(void)
{
	crossbarHook(23,0);
	return;
}

void crossbarHook_24_0(void)
{
	crossbarHook(24,0);
	return;
}

void crossbarHook_25_0(void)
{
	crossbarHook(25,0);
	return;
}

void crossbarHook_26_0(void)
{
	crossbarHook(26,0);
	return;
}

void crossbarHook_27_0(void)
{
	crossbarHook(27,0);
	return;
}

void crossbarHook_28_0(void)
{
	crossbarHook(28,0);
	return;
}

void crossbarHook_29_0(void)
{
	crossbarHook(29,0);
	return;
}

void crossbarHook_30_0(void)
{
	crossbarHook(30,0);
	return;
}

void crossbarHook_31_0(void)
{
	crossbarHook(31,0);
	return;
}

void crossbarHook_32_0(void)
{
	crossbarHook(32,0);
	return;
}

void crossbarHook_33_0(void)
{
	crossbarHook(33,0);
	return;
}

void crossbarHook_34_0(void)
{
	crossbarHook(34,0);
	return;
}

void crossbarHook_35_0(void)
{
	crossbarHook(35,0);
	return;
}

void crossbarHook_36_0(void)
{
	crossbarHook(36,0);
	return;
}

void crossbarHook_37_0(void)
{
	crossbarHook(37,0);
	return;
}

void crossbarHook_37_1(void)
{
	crossbarHook(37,1);
	return;
}

void crossbarHook_37_2(void)
{
	crossbarHook(37,2);
	return;
}

void crossbarHook_37_3(void)
{
	crossbarHook(37,3);
	return;
}

void crossbarHook_38_0(void)
{
	crossbarHook(38,0);
	return;
}

void crossbarHook_38_1(void)
{
	crossbarHook(38,1);
	return;
}

void crossbarHook_39_0(void)
{
	crossbarHook(39,0);
	return;
}

void crossbarHook_39_1(void)
{
	crossbarHook(39,1);
	return;
}

void crossbarHook_40_0(void)
{
	crossbarHook(40,0);
	return;
}

void crossbarHook_40_1(void)
{
	crossbarHook(40,1);
	return;
}

void crossbarHook_40_2(void)
{
	crossbarHook(40,2);
	return;
}

void crossbarHook_40_3(void)
{
	crossbarHook(40,3);
	return;
}

void crossbarHook_40_4(void)
{
	crossbarHook(40,4);
	return;
}

void crossbarHook_40_5(void)
{
	crossbarHook(40,5);
	return;
}

void crossbarHook_40_6(void)
{
	crossbarHook(40,6);
	return;
}

void crossbarHook_40_7(void)
{
	crossbarHook(40,7);
	return;
}

void crossbarHook_40_8(void)
{
	crossbarHook(40,8);
	return;
}

void crossbarHook_40_9(void)
{
	crossbarHook(40,9);
	return;
}

void crossbarHook_40_10(void)
{
	crossbarHook(40,10);
	return;
}

void crossbarHook_40_11(void)
{
	crossbarHook(40,11);
	return;
}

void crossbarHook_40_12(void)
{
	crossbarHook(40,12);
	return;
}

void crossbarHook_40_13(void)
{
	crossbarHook(40,13);
	return;
}

void crossbarHook_40_14(void)
{
	crossbarHook(40,14);
	return;
}

void crossbarHook_40_15(void)
{
	crossbarHook(40,15);
	return;
}

void crossbarHook_40_16(void)
{
	crossbarHook(40,16);
	return;
}

void crossbarHook_40_17(void)
{
	crossbarHook(40,17);
	return;
}

void crossbarHook_40_18(void)
{
	crossbarHook(40,18);
	return;
}

void crossbarHook_40_19(void)
{
	crossbarHook(40,19);
	return;
}

void crossbarHook_41_0(void)
{
	crossbarHook(41,0);
	return;
}

void crossbarHook_41_1(void)
{
	crossbarHook(41,1);
	return;
}

void crossbarHook_41_2(void)
{
	crossbarHook(41,2);
	return;
}

void crossbarHook_41_3(void)
{
	crossbarHook(41,3);
	return;
}

void crossbarHook_41_4(void)
{
	crossbarHook(41,4);
	return;
}

void crossbarHook_41_5(void)
{
	crossbarHook(41,5);
	return;
}

void crossbarHook_42_0(void)
{
	crossbarHook(42,0);
	return;
}

void crossbarHook_43_0(void)
{
	crossbarHook(43,0);
	return;
}

void crossbarHook_44_0(void)
{
	crossbarHook(44,0);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_1(void)
{
	crossbarHook(44,1);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_2(void)
{
	crossbarHook(44,2);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_3(void)
{
	crossbarHook(44,3);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_4(void)
{
	crossbarHook(44,4);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_5(void)
{
	crossbarHook(44,5);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_6(void)
{
	crossbarHook(44,6);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_7(void)
{
	crossbarHook(44,7);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_8(void)
{
	crossbarHook(44,8);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_9(void)
{
	crossbarHook(44,9);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_10(void)
{
	crossbarHook(44,10);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_11(void)
{
	crossbarHook(44,11);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_12(void)
{
	crossbarHook(44,12);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_13(void)
{
	crossbarHook(44,13);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_14(void)
{
	crossbarHook(44,14);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_15(void)
{
	crossbarHook(44,15);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_16(void)
{
	crossbarHook(44,16);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_17(void)
{
	crossbarHook(44,17);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_18(void)
{
	crossbarHook(44,18);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_19(void)
{
	crossbarHook(44,19);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_20(void)
{
	crossbarHook(44,20);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_21(void)
{
	crossbarHook(44,21);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_22(void)
{
	crossbarHook(44,22);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_44_23(void)
{
	crossbarHook(44,23);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_0(void)
{
	crossbarHook(45,0);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_1(void)
{
	crossbarHook(45,1);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_2(void)
{
	crossbarHook(45,2);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_3(void)
{
	crossbarHook(45,3);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_4(void)
{
	crossbarHook(45,4);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_5(void)
{
	crossbarHook(45,5);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_6(void)
{
	crossbarHook(45,6);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_7(void)
{
	crossbarHook(45,7);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_8(void)
{
	crossbarHook(45,8);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_9(void)
{
	crossbarHook(45,9);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_10(void)
{
	crossbarHook(45,10);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_11(void)
{
	crossbarHook(45,11);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_12(void)
{
	crossbarHook(45,12);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_13(void)
{
	crossbarHook(45,13);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_14(void)
{
	crossbarHook(45,14);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_15(void)
{
	crossbarHook(45,15);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_16(void)
{
	crossbarHook(45,16);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_17(void)
{
	crossbarHook(45,17);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_18(void)
{
	crossbarHook(45,18);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_19(void)
{
	crossbarHook(45,19);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_20(void)
{
	crossbarHook(45,20);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_21(void)
{
	crossbarHook(45,21);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_22(void)
{
	crossbarHook(45,22);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_45_23(void)
{
	crossbarHook(45,23);
	INIT_EXIT_FW_HOOK
	return;
}


