/* Generated by INTECRIO OS Configurator Plugin */
/* (c) 2004 ETAS (ETAS GmbH) */

#include "../a_basdef.h"

/*********** crossbar hooks ***************/

/* entries for crossbar task table */

/* crossbar hook in task 1 SWT_CAN1_AP_BMS_AIRs_State */
crossbarHookTableEntry crossbarHookTable1[1] = {NULL};

/* crossbar hook in task 2 SWT_CAN1_AP_BMS_ChargerParameters */
crossbarHookTableEntry crossbarHookTable2[1] = {NULL};

/* crossbar hook in task 3 SWT_CAN1_AP_BMS_SDC */
crossbarHookTableEntry crossbarHookTable3[1] = {NULL};

/* crossbar hook in task 4 SWT_CAN1_AP_BMS_Temperatures */
crossbarHookTableEntry crossbarHookTable4[1] = {NULL};

/* crossbar hook in task 5 SWT_CAN1_AP_BMS_Voltages */
crossbarHookTableEntry crossbarHookTable5[1] = {NULL};

/* crossbar hook in task 6 SWT_CAN1_AP_CurrentSensor */
crossbarHookTableEntry crossbarHookTable6[1] = {NULL};

/* crossbar hook in task 7 SWT_CAN1_AP_DASH_EnableDrive */
crossbarHookTableEntry crossbarHookTable7[1] = {NULL};

/* crossbar hook in task 8 SWT_CAN1_AP_DASH_Mode */
crossbarHookTableEntry crossbarHookTable8[1] = {NULL};

/* crossbar hook in task 9 SWT_CAN1_AP_DASH_PrechargeRequest */
crossbarHookTableEntry crossbarHookTable9[1] = {NULL};

/* crossbar hook in task 10 SWT_CAN1_AP_Inverter_L_Tx */
crossbarHookTableEntry crossbarHookTable10[1] = {NULL};

/* crossbar hook in task 11 SWT_CAN1_AP_Inverter_R_Tx */
crossbarHookTableEntry crossbarHookTable11[1] = {NULL};

/* crossbar hook in task 12 SWT_CAN1_NM_BMS_Keep_Alive */
crossbarHookTableEntry crossbarHookTable12[1] = {NULL};

/* crossbar hook in task 13 SWT_CAN1_NM_DASH_Keep_Alive */
crossbarHookTableEntry crossbarHookTable13[1] = {NULL};

/* crossbar hook in task 14 SWT_CAN2_AP_ELLIPSE_AUTO */
crossbarHookTableEntry crossbarHookTable14[1] = {NULL};

/* crossbar hook in task 15 SWT_CAN2_AP_ELLIPSE_EKF_EULER */
crossbarHookTableEntry crossbarHookTable15[1] = {NULL};

/* crossbar hook in task 16 SWT_CAN2_AP_ELLIPSE_EKF_POS */
crossbarHookTableEntry crossbarHookTable16[1] = {NULL};

/* crossbar hook in task 17 SWT_CAN2_AP_ELLIPSE_EKF_VEL */
crossbarHookTableEntry crossbarHookTable17[1] = {NULL};

/* crossbar hook in task 18 SWT_CAN2_AP_ELLIPSE_GPS_VEL */
crossbarHookTableEntry crossbarHookTable18[1] = {NULL};

/* crossbar hook in task 19 SWT_CAN2_AP_ELLIPSE_IMU_ACCEL */
crossbarHookTableEntry crossbarHookTable19[1] = {NULL};

/* crossbar hook in task 20 SWT_CAN2_AP_ELLIPSE_IMU_GYRO */
crossbarHookTableEntry crossbarHookTable20[1] = {NULL};

/* crossbar hook in task 21 SWT_CAN2_AP_ELLIPSE_VEL_Valid */
crossbarHookTableEntry crossbarHookTable21[1] = {NULL};

/* crossbar hook in task 22 SWT_CAN2_AP_FECU_Data1 */
crossbarHookTableEntry crossbarHookTable22[1] = {NULL};

/* crossbar hook in task 23 SWT_CAN2_AP_FECU_Data2 */
crossbarHookTableEntry crossbarHookTable23[1] = {NULL};

/* crossbar hook in task 24 SWT_CAN2_AP_RECU_Data */
crossbarHookTableEntry crossbarHookTable24[1] = {NULL};

/* crossbar hook in task 25 SWT_CAN2_MEAS_RECU_SDC */
crossbarHookTableEntry crossbarHookTable25[1] = {NULL};

/* crossbar hook in task 26 SWT_CAN2_NM_ELLIPSE_Status */
crossbarHookTableEntry crossbarHookTable26[1] = {NULL};

/* crossbar hook in task 27 SWT_CAN2_NM_FECU_Keep_Alive */
crossbarHookTableEntry crossbarHookTable27[1] = {NULL};

/* crossbar hook in task 28 SWT_CAN2_NM_RECU_Keep_Alive */
crossbarHookTableEntry crossbarHookTable28[1] = {NULL};

/* crossbar hook in task 29 Timer_1000ms */
crossbarHookTableEntry crossbarHookTable29[2] = {NULL, NULL};

/* crossbar hook in task 30 Timer_100ms */
crossbarHookTableEntry crossbarHookTable30[2] = {NULL, NULL};

/* crossbar hook in task 31 Timer_25ms */
crossbarHookTableEntry crossbarHookTable31[14] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 32 Timer_Inv */
crossbarHookTableEntry crossbarHookTable32[6] = {NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 33 Timer_Sync */
crossbarHookTableEntry crossbarHookTable33[4] = {NULL, NULL, NULL, NULL};

/* crossbar hook in task 34 ISR_CAN1 */
crossbarHookTableEntry crossbarHookTable34[1] = {NULL};

/* crossbar hook in task 35 ISR_CAN2 */
crossbarHookTableEntry crossbarHookTable35[1] = {NULL};

/* crossbar hook in task 36 Init */
crossbarHookTableEntry crossbarHookTable36[18] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

/* crossbar hook in task 37 Exit */
crossbarHookTableEntry crossbarHookTable37[18] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};


/* crossbar task table */
crossbarTaskTableEntry crossbarTaskTable[38] =
{
	{NULL},
	{&crossbarHookTable1[0]},
	{&crossbarHookTable2[0]},
	{&crossbarHookTable3[0]},
	{&crossbarHookTable4[0]},
	{&crossbarHookTable5[0]},
	{&crossbarHookTable6[0]},
	{&crossbarHookTable7[0]},
	{&crossbarHookTable8[0]},
	{&crossbarHookTable9[0]},
	{&crossbarHookTable10[0]},
	{&crossbarHookTable11[0]},
	{&crossbarHookTable12[0]},
	{&crossbarHookTable13[0]},
	{&crossbarHookTable14[0]},
	{&crossbarHookTable15[0]},
	{&crossbarHookTable16[0]},
	{&crossbarHookTable17[0]},
	{&crossbarHookTable18[0]},
	{&crossbarHookTable19[0]},
	{&crossbarHookTable20[0]},
	{&crossbarHookTable21[0]},
	{&crossbarHookTable22[0]},
	{&crossbarHookTable23[0]},
	{&crossbarHookTable24[0]},
	{&crossbarHookTable25[0]},
	{&crossbarHookTable26[0]},
	{&crossbarHookTable27[0]},
	{&crossbarHookTable28[0]},
	{&crossbarHookTable29[0]},
	{&crossbarHookTable30[0]},
	{&crossbarHookTable31[0]},
	{&crossbarHookTable32[0]},
	{&crossbarHookTable33[0]},
	{&crossbarHookTable34[0]},
	{&crossbarHookTable35[0]},
	{&crossbarHookTable36[0]},
	{&crossbarHookTable37[0]}
};

/* crossbar hook processes */
void crossbarHook_1_0(void)
{
	crossbarHook(1,0);
	return;
}

void crossbarHook_2_0(void)
{
	crossbarHook(2,0);
	return;
}

void crossbarHook_3_0(void)
{
	crossbarHook(3,0);
	return;
}

void crossbarHook_4_0(void)
{
	crossbarHook(4,0);
	return;
}

void crossbarHook_5_0(void)
{
	crossbarHook(5,0);
	return;
}

void crossbarHook_6_0(void)
{
	crossbarHook(6,0);
	return;
}

void crossbarHook_7_0(void)
{
	crossbarHook(7,0);
	return;
}

void crossbarHook_8_0(void)
{
	crossbarHook(8,0);
	return;
}

void crossbarHook_9_0(void)
{
	crossbarHook(9,0);
	return;
}

void crossbarHook_10_0(void)
{
	crossbarHook(10,0);
	return;
}

void crossbarHook_11_0(void)
{
	crossbarHook(11,0);
	return;
}

void crossbarHook_12_0(void)
{
	crossbarHook(12,0);
	return;
}

void crossbarHook_13_0(void)
{
	crossbarHook(13,0);
	return;
}

void crossbarHook_14_0(void)
{
	crossbarHook(14,0);
	return;
}

void crossbarHook_15_0(void)
{
	crossbarHook(15,0);
	return;
}

void crossbarHook_16_0(void)
{
	crossbarHook(16,0);
	return;
}

void crossbarHook_17_0(void)
{
	crossbarHook(17,0);
	return;
}

void crossbarHook_18_0(void)
{
	crossbarHook(18,0);
	return;
}

void crossbarHook_19_0(void)
{
	crossbarHook(19,0);
	return;
}

void crossbarHook_20_0(void)
{
	crossbarHook(20,0);
	return;
}

void crossbarHook_21_0(void)
{
	crossbarHook(21,0);
	return;
}

void crossbarHook_22_0(void)
{
	crossbarHook(22,0);
	return;
}

void crossbarHook_23_0(void)
{
	crossbarHook(23,0);
	return;
}

void crossbarHook_24_0(void)
{
	crossbarHook(24,0);
	return;
}

void crossbarHook_25_0(void)
{
	crossbarHook(25,0);
	return;
}

void crossbarHook_26_0(void)
{
	crossbarHook(26,0);
	return;
}

void crossbarHook_27_0(void)
{
	crossbarHook(27,0);
	return;
}

void crossbarHook_28_0(void)
{
	crossbarHook(28,0);
	return;
}

void crossbarHook_29_0(void)
{
	crossbarHook(29,0);
	return;
}

void crossbarHook_29_1(void)
{
	crossbarHook(29,1);
	return;
}

void crossbarHook_30_0(void)
{
	crossbarHook(30,0);
	return;
}

void crossbarHook_30_1(void)
{
	crossbarHook(30,1);
	return;
}

void crossbarHook_31_0(void)
{
	crossbarHook(31,0);
	return;
}

void crossbarHook_31_1(void)
{
	crossbarHook(31,1);
	return;
}

void crossbarHook_31_2(void)
{
	crossbarHook(31,2);
	return;
}

void crossbarHook_31_3(void)
{
	crossbarHook(31,3);
	return;
}

void crossbarHook_31_4(void)
{
	crossbarHook(31,4);
	return;
}

void crossbarHook_31_5(void)
{
	crossbarHook(31,5);
	return;
}

void crossbarHook_31_6(void)
{
	crossbarHook(31,6);
	return;
}

void crossbarHook_31_7(void)
{
	crossbarHook(31,7);
	return;
}

void crossbarHook_31_8(void)
{
	crossbarHook(31,8);
	return;
}

void crossbarHook_31_9(void)
{
	crossbarHook(31,9);
	return;
}

void crossbarHook_31_10(void)
{
	crossbarHook(31,10);
	return;
}

void crossbarHook_31_11(void)
{
	crossbarHook(31,11);
	return;
}

void crossbarHook_31_12(void)
{
	crossbarHook(31,12);
	return;
}

void crossbarHook_31_13(void)
{
	crossbarHook(31,13);
	return;
}

void crossbarHook_32_0(void)
{
	crossbarHook(32,0);
	return;
}

void crossbarHook_32_1(void)
{
	crossbarHook(32,1);
	return;
}

void crossbarHook_32_2(void)
{
	crossbarHook(32,2);
	return;
}

void crossbarHook_32_3(void)
{
	crossbarHook(32,3);
	return;
}

void crossbarHook_32_4(void)
{
	crossbarHook(32,4);
	return;
}

void crossbarHook_32_5(void)
{
	crossbarHook(32,5);
	return;
}

void crossbarHook_33_0(void)
{
	crossbarHook(33,0);
	return;
}

void crossbarHook_33_1(void)
{
	crossbarHook(33,1);
	return;
}

void crossbarHook_33_2(void)
{
	crossbarHook(33,2);
	return;
}

void crossbarHook_33_3(void)
{
	crossbarHook(33,3);
	return;
}

void crossbarHook_34_0(void)
{
	crossbarHook(34,0);
	return;
}

void crossbarHook_35_0(void)
{
	crossbarHook(35,0);
	return;
}

void crossbarHook_36_0(void)
{
	crossbarHook(36,0);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_1(void)
{
	crossbarHook(36,1);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_2(void)
{
	crossbarHook(36,2);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_3(void)
{
	crossbarHook(36,3);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_4(void)
{
	crossbarHook(36,4);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_5(void)
{
	crossbarHook(36,5);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_6(void)
{
	crossbarHook(36,6);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_7(void)
{
	crossbarHook(36,7);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_8(void)
{
	crossbarHook(36,8);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_9(void)
{
	crossbarHook(36,9);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_10(void)
{
	crossbarHook(36,10);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_11(void)
{
	crossbarHook(36,11);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_12(void)
{
	crossbarHook(36,12);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_13(void)
{
	crossbarHook(36,13);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_14(void)
{
	crossbarHook(36,14);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_15(void)
{
	crossbarHook(36,15);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_16(void)
{
	crossbarHook(36,16);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_36_17(void)
{
	crossbarHook(36,17);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_0(void)
{
	crossbarHook(37,0);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_1(void)
{
	crossbarHook(37,1);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_2(void)
{
	crossbarHook(37,2);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_3(void)
{
	crossbarHook(37,3);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_4(void)
{
	crossbarHook(37,4);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_5(void)
{
	crossbarHook(37,5);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_6(void)
{
	crossbarHook(37,6);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_7(void)
{
	crossbarHook(37,7);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_8(void)
{
	crossbarHook(37,8);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_9(void)
{
	crossbarHook(37,9);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_10(void)
{
	crossbarHook(37,10);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_11(void)
{
	crossbarHook(37,11);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_12(void)
{
	crossbarHook(37,12);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_13(void)
{
	crossbarHook(37,13);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_14(void)
{
	crossbarHook(37,14);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_15(void)
{
	crossbarHook(37,15);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_16(void)
{
	crossbarHook(37,16);
	INIT_EXIT_FW_HOOK
	return;
}

void crossbarHook_37_17(void)
{
	crossbarHook(37,17);
	INIT_EXIT_FW_HOOK
	return;
}


