set MATLAB=C:\Program Files\MATLAB\R2017b
@"rtw_build.bat" -f Disconnections_ETR07.mk  MODELLIB=Disconnections_ETR07lib.lib MODELREF_TARGET_TYPE=NONE ISPROTECTINGMODEL=NOTPROTECTING RELATIVE_PATH_TO_ANCHOR=.. MAT_FILE=0 IRTWaitForStartMsg=0
