/*****************************************************************************
 *
 * Accel_Data_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_Accel_Data_Obj *initModel_RTWTop_Accel_Data(void);
/* Level 1 class object declaration */
extern struct RTWTop_Accel_Data_Class RTWTop_Accel_Data_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_Accel_Data(struct RTWTop_Accel_Data_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_Accel_Data_Obj *initInstance_RTWTop_Accel_Data(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_Accel_Data(void);
/* Definition of the class structure */
struct RTWTop_Accel_Data_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionFX_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionFY_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionFZ_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionRX_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionRY_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_AccDataConversionRZ_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_LowPass_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_LowPass1_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_B_LowPass2_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_DW_A_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_DW_A_f_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_CycleTime_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_CycleTime_Gain_h_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_DataStoreMemory_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_DataStoreMemory_InitialValue_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_ExperimentalOffset_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_ExperimentalOffset_Value_e_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_Gain2_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_Gain4_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_RpsLSB_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_P_sbit_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_F_X_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_F_Y_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_F_Z_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_R_X_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_R_Y_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_ACCEL_R_Z_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_Gyroscope_F_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_U_Gyroscope_R_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_F_X_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_F_Y_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_F_Z_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_R_X_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_R_Y_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Accel_R_Z_SI_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Gyro_F_Z_Deg_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Gyro_R_Z_Deg_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Rate_F_Z_Degs2_Ptr;
    scalarWrapper_Obj *RTWWrapper_Accel_Data_Y_Rate_R_Z_Degs_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_Accel_Data_Obj
{
    ASDObjectHeader objectHeader;
};
