/*****************************************************************************
 *
 * APPS_Implausibility_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_APPS_Implausibility_Obj *initModel_RTWTop_APPS_Implausibility(void);
/* Level 1 class object declaration */
extern struct RTWTop_APPS_Implausibility_Class RTWTop_APPS_Implausibility_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_APPS_Implausibility(struct RTWTop_APPS_Implausibility_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_APPS_Implausibility_Obj *initInstance_RTWTop_APPS_Implausibility(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_APPS_Implausibility(void);
/* Definition of the class structure */
struct RTWTop_APPS_Implausibility_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_APPS_Implausibility_DW_ERROR_Counter_Ptr;
    scalarWrapper_Obj *RTWWrapper_APPS_Implausibility_U_APPS1_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_APPS_Implausibility_U_APPS2_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_APPS_Implausibility_Y_Disconnect_Fail_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_APPS_Implausibility_Obj
{
    ASDObjectHeader objectHeader;
};
