/*****************************************************************************
 *
 * Car_State_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_Car_State_Obj *initModel_RTWTop_Car_State(void);
/* Level 1 class object declaration */
extern struct RTWTop_Car_State_Class RTWTop_Car_State_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_Car_State(struct RTWTop_Car_State_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_Car_State_Obj *initInstance_RTWTop_Car_State(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_Car_State(void);
/* Definition of the class structure */
struct RTWTop_Car_State_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_Car_State_B_Merge_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_DW_A_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_CompareToConstant_const_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Constant_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Constant_Value_f_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Constant_Value_fl_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Constant_Value_k_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Constant_Value_kb_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_DataStoreMemory_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Gain_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_IfDCBUSnotbits_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Merge_InitialOutput_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Saturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_P_Saturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_AIRs_State_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Accumulator_Voltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_CANDisconnection_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_CurrentSensDisc_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_NTCDisconnection_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_OverTemperature_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_OverVoltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_UnderTemperature_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_BMSerror_UnderVoltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Critical_CAN_Disconnection_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_DashPrechargeRequest_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_EnableDrive_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_InvertersMinDCBus_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_InvertersSubscribed_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Lock_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_BMS_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_BOTS_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_BSPD_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_HVBOX_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_HVD_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_Inertia_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_InverterLIntck_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_InverterRIntck_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_PackageIntck_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_SetaCockpit_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_SetaLeft_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_SetaRight_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_TSMPIntck_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_U_Shutdown_TSMS_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_AIRs_Request_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_Car_OK_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_Car_State_f_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_CurrentPathDisconnectionFlag_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_InvertersAction_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_PrechargeAssert_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_Precharge_Percentage_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_Precharge_Voltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_ShutdownClosed_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_TorqueEnable_Ptr;
    scalarWrapper_Obj *RTWWrapper_Car_State_Y_errors_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_Car_State_Obj
{
    ASDObjectHeader objectHeader;
};
