/*****************************************************************************
 *
 * Car_State_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2024 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "Car_State.h"
#include "Car_State_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "Car_State_instances.h"
extern    B_Car_State_T Car_State_B;
extern    DW_Car_State_T Car_State_DW;
extern    ExtU_Car_State_T Car_State_U;
extern    ExtY_Car_State_T Car_State_Y;
/* Initialization of Simulink model */
struct RTWTop_Car_State_Obj *initModel_RTWTop_Car_State(void)
{
    struct RTWTop_Car_State_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_Car_State (&RTWTop_Car_State_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_Car_State();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_Car_State(struct RTWTop_Car_State_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_Car_State_B_InvertersAction_Ptr = initInstance_scalarWrapper((void*)&Car_State_B.InvertersAction, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_B_Merge_Ptr = initInstance_scalarWrapper((void*)&Car_State_B.Merge, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_DW_A_Ptr = initInstance_scalarWrapper((void*)&Car_State_DW.A, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_AIRs_State_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.AIRs_State, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_APPS1_Value_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.APPS1_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_Accumulator_Voltage_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.Accumulator_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_BrakePedal_Value_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.BrakePedal_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_Critical_CAN_Disconnection_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.Critical_CAN_Disconnection, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_EnableDrive_Order_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.EnableDrive_Order, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_InvertersMinDCBus_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.InvertersMinDCBus, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_InvertersSubscribed_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.InvertersSubscribed, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_PrechargeRequest_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.PrechargeRequest, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_U_Shutdown_PackageIntck_Ptr = initInstance_scalarWrapper((void*)&Car_State_U.Shutdown_PackageIntck, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_AIRs_Request_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.AIRs_Request, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_Car_OK_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.Car_OK, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_Car_State_b_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.Car_State_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_InvertersAction_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.InvertersAction, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_PrechargeAssert_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.PrechargeAssert, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_Precharge_Percentage_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.Precharge_Percentage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_Precharge_Voltage_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.Precharge_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_Relay_Error_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.Relay_Error, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_TorqueEnable_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.TorqueEnable, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Car_State_Y_errors_Ptr = initInstance_scalarWrapper((void*)&Car_State_Y.errors, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_Car_State(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_Car_State_ClassMethodList =
{
    (MethodPtr)_L1_getPid_Car_State
};
/* Definition of the class header */
static ASDClassHeader RTWTop_Car_State_ClassHeader =
    {0, 1, 0, 23 + 0, (MethodList *)0, (MethodList *)&RTWTop_Car_State_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_Car_State_Class RTWTop_Car_State_ClassObj = {{1, {&RTWTop_Car_State_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_Car_State_Obj *initInstance_RTWTop_Car_State(void)
{
    struct RTWTop_Car_State_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_Car_State);
    return self;
}
void setDeltaT_Car_State(void)
{
}
