/*****************************************************************************
 *
 * Disconnections_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
#define bool RTW_bool
#include "Disconnections.h"
#include "Disconnections_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "Disconnections_instances.h"
extern    B_Disconnections_T Disconnections_B;
extern    DW_Disconnections_T Disconnections_DW;
extern    P_Disconnections_T Disconnections_P;
extern    ExtU_Disconnections_T Disconnections_U;
extern    ExtY_Disconnections_T Disconnections_Y;
/* Initialization of Simulink model */
struct RTWTop_Disconnections_Obj *initModel_RTWTop_Disconnections(void)
{
    struct RTWTop_Disconnections_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_Disconnections (&RTWTop_Disconnections_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_Disconnections();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_Disconnections(struct RTWTop_Disconnections_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_Disconnections_B_Merge_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_b_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_d_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_f_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_f, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_h_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_h, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_he_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_he, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_B_Merge_j_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_B.Merge_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_A_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.A, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_a_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_a, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_ar_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_ar, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_c_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_c0_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_c0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_g_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_g, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_gx_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_gx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_j_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_je_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_je, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_l_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_l, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Last_alive_o_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Last_alive_o, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Tot_Errors_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Tot_Errors, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Tot_Errors_h_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Tot_Errors_h, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Tot_Errors_j_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Tot_Errors_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Tot_Errors_k_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Tot_Errors_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_DW_Tot_Errors_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_DW.Tot_Errors_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_P_Constant_Value_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_c_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_d_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_e_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_h_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_i_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_ic_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_ic, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_j_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_l_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Constant_Value_o_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Constant_Value_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory1_InitialValue_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory1_InitialValue, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory1_InitialValue_b_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory1_InitialValue_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory1_InitialValue_c_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory1_InitialValue_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory1_InitialValue_d_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory1_InitialValue_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory1_InitialValue_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory1_InitialValue_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_b_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_ba_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_ba, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_c_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_d_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_f_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_j_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_jc_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_jc, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_k_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_kg_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_kg, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_ks_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_ks, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_DataStoreMemory_InitialValue_o_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.DataStoreMemory_InitialValue_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_a_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_b_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_l_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_m_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_o_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_P_Merge_InitialOutput_p_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_P.Merge_InitialOutput_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Disconnections_U_ADCAN_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.ADCAN_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_APPS1_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.APPS1_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_APPS2_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.APPS2_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Accel_F_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Accel_F_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Accel_R_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Accel_R_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_BMS_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.BMS_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_BrakeSensor_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.BrakeSensor_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Dash_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Dash_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Gyroscope_F_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Gyroscope_F, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Gyroscope_R_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Gyroscope_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_LV_Derivation_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.LV_Derivation_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Shutdown_Alive_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Shutdown_Alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_SteeringSensor_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.SteeringSensor_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Susp_F_L_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Susp_F_L_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Susp_F_R_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Susp_F_R_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Susp_R_L_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Susp_R_L_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_U_Susp_R_R_Bits_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_U.Susp_R_R_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_CounterOut_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.CounterOut, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_CriticalDisconnection_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.CriticalDisconnection, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Critical_CAN_Disconnection_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Critical_CAN_Disconnection, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Critical_Signal_Disconnection_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Critical_Signal_Disconnection, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_ADCAN_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_ADCAN, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_APPS1_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_APPS1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_APPS2_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_APPS2, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Accel_F_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Accel_F, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Accel_R_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Accel_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_BMS_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_BMS, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Brake_Sensor_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Brake_Sensor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_DashBoard_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_DashBoard, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Gyroscope_F_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Gyroscope_F, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Gyroscope_R_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Gyroscope_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_LV_Derivation_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_LV_Derivation, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Shutdown_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Shutdown, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_SteeringSensor_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_SteeringSensor, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Susp_F_L_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Susp_F_L, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Susp_F_R_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Susp_F_R, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Susp_R_L_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Susp_R_L, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_Disconnection_Susp_R_R_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.Disconnection_Susp_R_R, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Disconnections_Y_TV_mode_Ptr = initInstance_scalarWrapper((uint32)&Disconnections_Y.TV_mode, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_Disconnections(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_Disconnections_ClassMethodList =
{
    (MethodPtr)_L1_getPid_Disconnections
};
/* Definition of the class header */
static ASDClassHeader RTWTop_Disconnections_ClassHeader =
    {0, 1, 0, 100 + 0, (MethodList *)0, (MethodList *)&RTWTop_Disconnections_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_Disconnections_Class RTWTop_Disconnections_ClassObj = {{1, {&RTWTop_Disconnections_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_Disconnections_Obj *initInstance_RTWTop_Disconnections(void)
{
    struct RTWTop_Disconnections_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_Disconnections);
    return self;
}
void setDeltaT_Disconnections(void)
{
}
