/*****************************************************************************
 *
 * Ellipse_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_Ellipse_Obj *initModel_RTWTop_Ellipse(void);
/* Level 1 class object declaration */
extern struct RTWTop_Ellipse_Class RTWTop_Ellipse_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_Ellipse(struct RTWTop_Ellipse_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_Ellipse_Obj *initInstance_RTWTop_Ellipse(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_Ellipse(void);
/* Definition of the class structure */
struct RTWTop_Ellipse_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_X_IMU_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_X_MAG_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_Y_IMU_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_Y_MAG_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_Z_IMU_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ACCEL_Z_MAG_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ANGLE_SLIP_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ANGLE_TRACK_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_AUTO_STATUS_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_CLOCK_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_CURVATURE_RADIUS_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_GENERAL_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_GYRO_X_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_GYRO_Y_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_GYRO_Z_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_LATITUDE_EKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_LONGITUDE_EKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_PITCH_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_ROLL_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_TIME_STAMP_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_YAW_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_el_Vel_X_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_el_Vel_Y_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_U_el_Vel_Z_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_X_IMU_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_X_Mag_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_Y_IMU_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_Y_Mag_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_Z_IMU_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Accel_Z_Mag_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Clock_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_CurvRadius_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_General_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Gyro_X_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Gyro_Y_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Gyro_Z_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Lat_EKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Long_EKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Pitch_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Roll_Tx_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_SlipAngle_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Status_Auto_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Time_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_TrackAngle_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Vel_X_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Vel_Y_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Vel_Z_Ptr;
    scalarWrapper_Obj *RTWWrapper_Ellipse_Y_Yaw_Tx_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_Ellipse_Obj
{
    ASDObjectHeader objectHeader;
};
