/*****************************************************************************
 *
 * Ellipse_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
#define bool RTW_bool
#include "Ellipse.h"
#include "Ellipse_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "Ellipse_instances.h"
extern    ExtU_Ellipse_T Ellipse_U;
extern    ExtY_Ellipse_T Ellipse_Y;
/* Initialization of Simulink model */
struct RTWTop_Ellipse_Obj *initModel_RTWTop_Ellipse(void)
{
    struct RTWTop_Ellipse_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_Ellipse (&RTWTop_Ellipse_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_Ellipse();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_Ellipse(struct RTWTop_Ellipse_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_Ellipse_U_ACCEL_X_IMU_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_X_IMU, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ACCEL_X_MAG_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_X_MAG, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ACCEL_Y_IMU_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_Y_IMU, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ACCEL_Y_MAG_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_Y_MAG, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ACCEL_Z_IMU_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_Z_IMU, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ACCEL_Z_MAG_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ACCEL_Z_MAG, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ANGLE_SLIP_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ANGLE_SLIP, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ANGLE_TRACK_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ANGLE_TRACK, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_AUTO_STATUS_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.AUTO_STATUS, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_CLOCK_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.CLOCK, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_CURVATURE_RADIUS_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.CURVATURE_RADIUS, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_GENERAL_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.GENERAL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_GYRO_X_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.GYRO_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_GYRO_Y_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.GYRO_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_GYRO_Z_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.GYRO_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_LATITUDE_EKF_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.LATITUDE_EKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_LONGITUDE_EKF_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.LONGITUDE_EKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_PITCH_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.PITCH, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_ROLL_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.ROLL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_TIME_STAMP_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.TIME_STAMP, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_YAW_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.YAW, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_el_Vel_X_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.el_Vel_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_el_Vel_Y_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.el_Vel_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_U_el_Vel_Z_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_U.el_Vel_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_X_IMU_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_X_IMU_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_X_Mag_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_X_Mag_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_Y_IMU_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_Y_IMU_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_Y_Mag_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_Y_Mag_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_Z_IMU_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_Z_IMU_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Accel_Z_Mag_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Accel_Z_Mag_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Clock_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Clock_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_CurvRadius_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.CurvRadius, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_General_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.General_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Gyro_X_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Gyro_X_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Gyro_Y_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Gyro_Y_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Gyro_Z_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Gyro_Z_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Lat_EKF_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Lat_EKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Long_EKF_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Long_EKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Pitch_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Pitch_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Roll_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Roll_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_SlipAngle_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.SlipAngle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Status_Auto_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Status_Auto, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Time_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Time, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_TrackAngle_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.TrackAngle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Vel_X_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Vel_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Vel_Y_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Vel_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Vel_Z_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Vel_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Ellipse_Y_Yaw_Tx_Ptr = initInstance_scalarWrapper((uint32)&Ellipse_Y.Yaw_Tx, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_Ellipse(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_Ellipse_ClassMethodList =
{
    (MethodPtr)_L1_getPid_Ellipse
};
/* Definition of the class header */
static ASDClassHeader RTWTop_Ellipse_ClassHeader =
    {0, 1, 0, 48 + 0, (MethodList *)0, (MethodList *)&RTWTop_Ellipse_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_Ellipse_Class RTWTop_Ellipse_ClassObj = {{1, {&RTWTop_Ellipse_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_Ellipse_Obj *initInstance_RTWTop_Ellipse(void)
{
    struct RTWTop_Ellipse_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_Ellipse);
    return self;
}
void setDeltaT_Ellipse(void)
{
}
