/*****************************************************************************
 *
 * Inverters_Action_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_Inverters_Action_Obj *initModel_RTWTop_Inverters_Action(void);
/* Level 1 class object declaration */
extern struct RTWTop_Inverters_Action_Class RTWTop_Inverters_Action_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_Inverters_Action(struct RTWTop_Inverters_Action_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_Inverters_Action_Obj *initInstance_RTWTop_Inverters_Action(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_Inverters_Action(void);
/* Definition of the class structure */
struct RTWTop_Inverters_Action_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_B_Merge_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_B_Merge2_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_B_Merge2_p_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_B_subscribed_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_B_subscribed_b_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_DW_EnumerationCounter_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_DW_EnumerationCounter_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_DW_LastAction_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_DW_LastAction_k_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Constant_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Constant_Value_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_DataStoreMemory1_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_DataStoreMemory1_InitialValue_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_DataStoreMemory2_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_DataStoreMemory2_InitialValue_c_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Delay_DelayLength_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Delay_DelayLength_h_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Delay_InitialCondition_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Delay_InitialCondition_o_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_Merge_InitialOutput_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_TimeInterval_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_TimeInterval_Value_d_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P__Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_subscribed_InitialOutput_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_subscribed_InitialOutput_k_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_P_u_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_U_InvertersAction_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_U_current_L_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_U_current_R_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_L_RegID_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_L_b15tob8_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_L_b7tob0_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_R_RegID_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_R_b15tob8_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_Inverter_R_b7tob0_Ptr;
    scalarWrapper_Obj *RTWWrapper_Inverters_Action_Y_InvertersSubscribed_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_Inverters_Action_Obj
{
    ASDObjectHeader objectHeader;
};
