/*****************************************************************************
 *
 * Inverters_Data_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2024 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "Inverters_Data.h"
#include "Inverters_Data_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "Inverters_Data_instances.h"
extern    DW_Inverters_Data_T Inverters_Data_DW;
extern    ExtU_Inverters_Data_T Inverters_Data_U;
extern    ExtY_Inverters_Data_T Inverters_Data_Y;
/* Initialization of Simulink model */
struct RTWTop_Inverters_Data_Obj *initModel_RTWTop_Inverters_Data(void)
{
    struct RTWTop_Inverters_Data_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_Inverters_Data (&RTWTop_Inverters_Data_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_Inverters_Data();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_Inverters_Data(struct RTWTop_Inverters_Data_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_Inverters_Data_DW_Last_alive_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_DW.Last_alive, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_DW_Last_alive_h_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_DW.Last_alive_h, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_DW_Tot_Errors_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_DW.Tot_Errors, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_DW_Tot_Errors_c_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_DW.Tot_Errors_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_L_RegID_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_L_RegID, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_L_RegID_M235_Inv_L_DCBus_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_L_RegID_M235_Inv_L_DCBus, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_L_RegID_M48_Inv_L_Speed_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_L_RegID_M48_Inv_L_Speed, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_L_RegID_M73_Inv_L_TempMotor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_L_RegID_M73_Inv_L_TempMotor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_L_RegID_M74_Inv_L_TempIGBT_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_L_RegID_M74_Inv_L_TempIGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_R_RegID_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_R_RegID, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_R_RegID_M235_Inv_R_DCBus_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_R_RegID_M235_Inv_R_DCBus, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_R_RegID_M48_Inv_R_Speed_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_R_RegID_M48_Inv_R_Speed, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_R_RegID_M73_Inv_R_TempMotor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_R_RegID_M73_Inv_R_TempMotor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_U_Inv_R_RegID_M74_Inv_R_TempIGBT_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_U.Inv_R_RegID_M74_Inv_R_TempIGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Disconnection_InvL_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Disconnection_InvL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Disconnection_InvR_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Disconnection_InvR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Inv_L_TempIGBT_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Inv_L_TempIGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Inv_L_TempMotor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Inv_L_TempMotor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Inv_R_TempIGBT_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Inv_R_TempIGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Inv_R_TempMotor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Inv_R_TempMotor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_InvertersMinDCBus_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.InvertersMinDCBus, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Max_Temp_IGBT_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Max_Temp_IGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Max_Temp_Motors_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Max_Temp_Motors, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_RL_Vel_ms_Wheel_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.RL_Vel_ms_Wheel, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_RL_rads_Motor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.RL_rads_Motor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_RR_Vel_ms_Wheel_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.RR_Vel_ms_Wheel, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_RR_rads_Motor_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.RR_rads_Motor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Inverters_Data_Y_Speed_Ptr = initInstance_scalarWrapper((void*)&Inverters_Data_Y.Speed, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_Inverters_Data(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_Inverters_Data_ClassMethodList =
{
    (MethodPtr)_L1_getPid_Inverters_Data
};
/* Definition of the class header */
static ASDClassHeader RTWTop_Inverters_Data_ClassHeader =
    {0, 1, 0, 28 + 0, (MethodList *)0, (MethodList *)&RTWTop_Inverters_Data_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_Inverters_Data_Class RTWTop_Inverters_Data_ClassObj = {{1, {&RTWTop_Inverters_Data_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_Inverters_Data_Obj *initInstance_RTWTop_Inverters_Data(void)
{
    struct RTWTop_Inverters_Data_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_Inverters_Data);
    return self;
}
void setDeltaT_Inverters_Data(void)
{
}
