/*****************************************************************************
 *
 * LVD_Data_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_LVD_Data_Obj *initModel_RTWTop_LVD_Data(void);
/* Level 1 class object declaration */
extern struct RTWTop_LVD_Data_Class RTWTop_LVD_Data_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_LVD_Data(struct RTWTop_LVD_Data_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_LVD_Data_Obj *initInstance_RTWTop_LVD_Data(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_LVD_Data(void);
/* Definition of the class structure */
struct RTWTop_LVD_Data_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_DW_Previous_IN_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_DW_Previous_OUT_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_DataStoreMemory1_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_DataStoreMemory_InitialValue_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_MaxBits2_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_MaxBits_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_Vmax_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_Vmin_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_ct_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_P_exptcycletau1_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_U_LVBattery_Voltage_Bits_Ptr;
    scalarWrapper_Obj *RTWWrapper_LVD_Data_Y_LVbattery_Voltage_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_LVD_Data_Obj
{
    ASDObjectHeader objectHeader;
};
