/*****************************************************************************
 *
 * racing_modes_R2022a_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_racing_modes_R2022a_Obj *initModel_RTWTop_racing_modes_R2022a(void);
/* Level 1 class object declaration */
extern struct RTWTop_racing_modes_R2022a_Class RTWTop_racing_modes_R2022a_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_racing_modes_R2022a(struct RTWTop_racing_modes_R2022a_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_racing_modes_R2022a_Obj *initInstance_RTWTop_racing_modes_R2022a(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_racing_modes_R2022a(void);
/* Definition of the class structure */
struct RTWTop_racing_modes_R2022a_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_B_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_B_Merge_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_U_CustomMode_Data_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_U_CustomMode_Identifier_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_U_RacingMode_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_Y_VDC_Max_tire_slip_Ptr;
    scalarWrapper_Obj *RTWWrapper_racing_modes_R2022a_Y_Workshop_Mode_Enable_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_racing_modes_R2022a_Obj
{
    ASDObjectHeader objectHeader;
};
