/*****************************************************************************
 *
 * racing_modes_R2022a_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "racing_modes_R2022a.h"
#include "racing_modes_R2022a_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "racing_modes_R2022a_instances.h"
extern    B_racing_modes_R2022a_T racing_modes_R2022a_B;
extern    ExtU_racing_modes_R2022a_T racing_modes_R2022a_U;
extern    ExtY_racing_modes_R2022a_T racing_modes_R2022a_Y;
/* Initialization of Simulink model */
struct RTWTop_racing_modes_R2022a_Obj *initModel_RTWTop_racing_modes_R2022a(void)
{
    struct RTWTop_racing_modes_R2022a_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_racing_modes_R2022a (&RTWTop_racing_modes_R2022a_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_racing_modes_R2022a();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_racing_modes_R2022a(struct RTWTop_racing_modes_R2022a_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_racing_modes_R2022a_B_Gain_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_B.Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_B_Merge_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_B.Merge, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_U_CustomMode_Data_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_U.CustomMode_Data, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_U_CustomMode_Identifier_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_U.CustomMode_Identifier, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_U_RacingMode_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_U.RacingMode, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_Y_VDC_Max_tire_slip_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_Y.VDC_Max_tire_slip, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_racing_modes_R2022a_Y_Workshop_Mode_Enable_Ptr = initInstance_scalarWrapper((void*)&racing_modes_R2022a_Y.Workshop_Mode_Enable, sizeof(char), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_racing_modes_R2022a(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_racing_modes_R2022a_ClassMethodList =
{
    (MethodPtr)_L1_getPid_racing_modes_R2022a
};
/* Definition of the class header */
static ASDClassHeader RTWTop_racing_modes_R2022a_ClassHeader =
    {0, 1, 0, 7 + 0, (MethodList *)0, (MethodList *)&RTWTop_racing_modes_R2022a_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_racing_modes_R2022a_Class RTWTop_racing_modes_R2022a_ClassObj = {{1, {&RTWTop_racing_modes_R2022a_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_racing_modes_R2022a_Obj *initInstance_RTWTop_racing_modes_R2022a(void)
{
    struct RTWTop_racing_modes_R2022a_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_racing_modes_R2022a);
    return self;
}
void setDeltaT_racing_modes_R2022a(void)
{
}
