/*****************************************************************************
 *
 * SoC_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_SoC_Obj *initModel_RTWTop_SoC(void);
/* Level 1 class object declaration */
extern struct RTWTop_SoC_Class RTWTop_SoC_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_SoC(struct RTWTop_SoC_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_SoC_Obj *initInstance_RTWTop_SoC(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_SoC(void);
/* Definition of the class structure */
struct RTWTop_SoC_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_SoC_B_Memory_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_B_Memory_p_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_B_NOT_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_B_NOT_p_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_B_Switch_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_B_Switch_d_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Constant_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Constant_Value_j_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Gain1_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Gain_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Gain_Gain_e_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Integrator_IC_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Integrator_IC_d_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Memory_InitialCondition_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Memory_InitialCondition_o_Ptr;
    vectorWrapper_Obj *RTWWrapper_SoC_P_OCVtoSoC_bp01Data_Ptr;
    vectorWrapper_Obj *RTWWrapper_SoC_P_OCVtoSoC_bp01Data_n_Ptr;
    vectorWrapper_Obj *RTWWrapper_SoC_P_OCVtoSoC_tableData_Ptr;
    vectorWrapper_Obj *RTWWrapper_SoC_P_OCVtoSoC_tableData_k_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Saturation1_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Saturation1_LowerSat_e_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Saturation1_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_P_Saturation1_UpperSat_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_U_Accumulator_Current_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_U_Car_State_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_U_Highest_CellVoltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_U_Lowest_CellVoltage_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_Y_SoC_Avg_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_Y_SoC_High_Ptr;
    scalarWrapper_Obj *RTWWrapper_SoC_Y_SoC_Low_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_SoC_Obj
{
    ASDObjectHeader objectHeader;
};
