/*****************************************************************************
 *
 * SoC_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
#define bool RTW_bool
#include "SoC.h"
#include "SoC_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "SoC_instances.h"
extern    B_SoC_T SoC_B;
extern    DW_SoC_T SoC_DW;
extern    P_SoC_T SoC_P;
extern    ExtU_SoC_T SoC_U;
extern    ExtY_SoC_T SoC_Y;
/* Initialization of Simulink model */
struct RTWTop_SoC_Obj *initModel_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_SoC (&RTWTop_SoC_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_SoC();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_SoC(struct RTWTop_SoC_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_SoC_B_Memory_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.Memory, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Memory_p_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.Memory_p, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_NOT_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.NOT, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_NOT_p_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.NOT_p, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Switch_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.Switch, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Switch_d_Ptr = initInstance_scalarWrapper((uint32)&SoC_B.Switch_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_P_Constant_Value_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Constant_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Constant_Value_j_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Constant_Value_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Gain1_Gain_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Gain1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Gain_Gain_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Gain_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Gain_Gain_e_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Gain_Gain_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Integrator_IC_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Integrator_IC, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Integrator_IC_d_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Integrator_IC_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Memory_InitialCondition_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Memory_InitialCondition, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Memory_InitialCondition_o_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Memory_InitialCondition_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_OCVtoSoC_bp01Data_Ptr = initInstance_vectorWrapper((uint32)&SoC_P.OCVtoSoC_bp01Data, sizeof(double), (uint32)26, (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_OCVtoSoC_bp01Data_n_Ptr = initInstance_vectorWrapper((uint32)&SoC_P.OCVtoSoC_bp01Data_n, sizeof(double), (uint32)26, (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_OCVtoSoC_tableData_Ptr = initInstance_vectorWrapper((uint32)&SoC_P.OCVtoSoC_tableData, sizeof(double), (uint32)26, (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_OCVtoSoC_tableData_k_Ptr = initInstance_vectorWrapper((uint32)&SoC_P.OCVtoSoC_tableData_k, sizeof(double), (uint32)26, (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Saturation1_LowerSat_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Saturation1_LowerSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Saturation1_LowerSat_e_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Saturation1_LowerSat_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Saturation1_UpperSat_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Saturation1_UpperSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_P_Saturation1_UpperSat_m_Ptr = initInstance_scalarWrapper((uint32)&SoC_P.Saturation1_UpperSat_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_SoC_U_Accumulator_Current_Ptr = initInstance_scalarWrapper((uint32)&SoC_U.Accumulator_Current, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Car_State_Ptr = initInstance_scalarWrapper((uint32)&SoC_U.Car_State, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Highest_CellVoltage_Ptr = initInstance_scalarWrapper((uint32)&SoC_U.Highest_CellVoltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Lowest_CellVoltage_Ptr = initInstance_scalarWrapper((uint32)&SoC_U.Lowest_CellVoltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Avg_Ptr = initInstance_scalarWrapper((uint32)&SoC_Y.SoC_Avg, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_High_Ptr = initInstance_scalarWrapper((uint32)&SoC_Y.SoC_High, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Low_Ptr = initInstance_scalarWrapper((uint32)&SoC_Y.SoC_Low, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_SoC(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_SoC_ClassMethodList =
{
    (MethodPtr)_L1_getPid_SoC
};
/* Definition of the class header */
static ASDClassHeader RTWTop_SoC_ClassHeader =
    {0, 1, 0, 30 + 0, (MethodList *)0, (MethodList *)&RTWTop_SoC_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_SoC_Class RTWTop_SoC_ClassObj = {{1, {&RTWTop_SoC_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_SoC_Obj *initInstance_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_SoC);
    return self;
}
void setDeltaT_SoC(void)
{
}
