/*****************************************************************************
 *
 * SoC_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2024 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "SoC.h"
#include "SoC_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "SoC_instances.h"
extern    B_SoC_T SoC_B;
extern    ConstB_SoC_T SoC_ConstB;
extern    DW_SoC_T SoC_DW;
extern    ExtU_SoC_T SoC_U;
extern    ExtY_SoC_T SoC_Y;
/* Initialization of Simulink model */
struct RTWTop_SoC_Obj *initModel_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_SoC (&RTWTop_SoC_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_SoC();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_SoC(struct RTWTop_SoC_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_SoC_B_AccuOCVtoSOC2024_Ptr = initInstance_scalarWrapper((void*)&SoC_B.AccuOCVtoSOC2024, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CellOCVtoSOC2024_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CellOCVtoSOC2024, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Pdot_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys[0].Pdot[0], sizeof(double), (uint32)4, (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Sum2_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys[0].Sum2, sizeof(double), (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__TmpSignalConversionAtIntegrator_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys[0].TmpSignalConversionAtIntegrator, sizeof(double), (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_p_0__Pdot_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys_p[0].Pdot[0], sizeof(double), (uint32)4, (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_p_0__Sum2_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CoreSubsys_p[0].Sum2, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_p_0__Sum2_c_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys_p[0].Sum2_c, sizeof(double), (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_p_0__TmpSignalConversionAtIntegrator_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys_p[0].TmpSignalConversionAtIntegrator, sizeof(double), (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_ConstB_CoreSubsys_Divide_Ptr = initInstance_scalarWrapper((void*)&SoC_ConstB.CoreSubsys.Divide, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_ConstB_CoreSubsys_p_Divide_Ptr = initInstance_scalarWrapper((void*)&SoC_ConstB.CoreSubsys_p.Divide, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Accumulator_Current_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Accumulator_Current, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Accumulator_Voltage_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Accumulator_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Average_CellTemp_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Average_CellTemp, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Lowest_CellVoltage_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Lowest_CellVoltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Avg_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_Avg, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_KF_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_KF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Low_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_Low, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_SoC(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_SoC_ClassMethodList =
{
    (MethodPtr)_L1_getPid_SoC
};
/* Definition of the class header */
static ASDClassHeader RTWTop_SoC_ClassHeader =
    {0, 1, 0, 18 + 0, (MethodList *)0, (MethodList *)&RTWTop_SoC_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_SoC_Class RTWTop_SoC_ClassObj = {{1, {&RTWTop_SoC_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_SoC_Obj *initInstance_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_SoC);
    return self;
}
void setDeltaT_SoC(void)
{
}
