/*****************************************************************************
 *
 * SoC_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2024 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "SoC.h"
#include "SoC_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "SoC_instances.h"
extern    B_SoC_T SoC_B;
extern    DW_SoC_T SoC_DW;
extern    ExtU_SoC_T SoC_U;
extern    ExtY_SoC_T SoC_Y;
/* Initialization of Simulink model */
struct RTWTop_SoC_Obj *initModel_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_SoC (&RTWTop_SoC_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_SoC();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_SoC(struct RTWTop_SoC_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_SoC_B_CoreSubsys_0__Assignment2_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys[0].Assignment2[0], sizeof(double), (uint32)5, (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__CoreSubsys_4__Probe_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys[0].CoreSubsys[4].Probe, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Gain_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CoreSubsys[0].Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__ImpAsg_InsertedFor_xk1_at_inpor_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys[0].ImpAsg_InsertedFor_xk1_at_inpor[0], sizeof(double), (uint32)5, (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Pk1_k1_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys[0].Pk1_k1[0], sizeof(double), (uint32)2, (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__RateTransition1_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CoreSubsys[0].RateTransition1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Reshape_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys[0].Reshape, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_0__Sum_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys[0].Sum, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__Gain_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CoreSubsys_g[0].Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__Probe_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys_g[0].Probe, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__Product5_Ptr = initInstance_matrixWrapper((void*)&SoC_B.CoreSubsys_g[0].Product5[0], sizeof(double), (uint32)2, (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__RateTransition1_Ptr = initInstance_scalarWrapper((void*)&SoC_B.CoreSubsys_g[0].RateTransition1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__Sum_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys_g[0].Sum, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_CoreSubsys_g_0__TmpSignalConversionAtDelayInpor_Ptr = initInstance_vectorWrapper((void*)&SoC_B.CoreSubsys_g[0].TmpSignalConversionAtDelayInpor, sizeof(double), (uint32)2, (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_SOCEstimatorCoulombCounting_0__CoreSubsys_Gain_Ptr = initInstance_scalarWrapper((void*)&SoC_B.SOCEstimatorCoulombCounting[0].CoreSubsys.Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_SOCEstimatorCoulombCounting_p_0__CoreSubsys_Gain_Ptr = initInstance_scalarWrapper((void*)&SoC_B.SOCEstimatorCoulombCounting_p[0].CoreSubsys.Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Saturation1_Ptr = initInstance_scalarWrapper((void*)&SoC_B.Saturation1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Saturation1_i_Ptr = initInstance_scalarWrapper((void*)&SoC_B.Saturation1_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Switch_Ptr = initInstance_scalarWrapper((void*)&SoC_B.Switch, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_B_Switch_d_Ptr = initInstance_scalarWrapper((void*)&SoC_B.Switch_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Accumulator_Current_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Accumulator_Current, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Car_State_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Car_State, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Highest_Cell_Voltage_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Highest_Cell_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_U_Lowest_Cell_Voltage_Ptr = initInstance_scalarWrapper((void*)&SoC_U.Lowest_Cell_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_CSoC_H_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.CSoC_H, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_CSoC_L_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.CSoC_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_KFSoC_H_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.KFSoC_H, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_KFSoC_L_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.KFSoC_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Avg_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_Avg, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_High_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_High, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_SoC_Y_SoC_Low_Ptr = initInstance_scalarWrapper((void*)&SoC_Y.SoC_Low, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_SoC(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_SoC_ClassMethodList =
{
    (MethodPtr)_L1_getPid_SoC
};
/* Definition of the class header */
static ASDClassHeader RTWTop_SoC_ClassHeader =
    {0, 1, 0, 31 + 0, (MethodList *)0, (MethodList *)&RTWTop_SoC_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_SoC_Class RTWTop_SoC_ClassObj = {{1, {&RTWTop_SoC_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_SoC_Obj *initInstance_RTWTop_SoC(void)
{
    struct RTWTop_SoC_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_SoC);
    return self;
}
void setDeltaT_SoC(void)
{
}
