/*****************************************************************************
 *
 * Torque_Control_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
#define bool RTW_bool
#include "Torque_Control.h"
#include "Torque_Control_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "Torque_Control_instances.h"
extern    B_Torque_Control_T Torque_Control_B;
extern    DW_Torque_Control_T Torque_Control_DW;
extern    P_Torque_Control_T Torque_Control_P;
extern    ExtU_Torque_Control_T Torque_Control_U;
extern    ExtY_Torque_Control_T Torque_Control_Y;
/* Initialization of Simulink model */
struct RTWTop_Torque_Control_Obj *initModel_RTWTop_Torque_Control(void)
{
    struct RTWTop_Torque_Control_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_Torque_Control (&RTWTop_Torque_Control_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_Torque_Control();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_Torque_Control(struct RTWTop_Torque_Control_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_Torque_Control_B_Abs_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Abs, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_BrakingwithRegenerative_sf_MATLABFunction_RegTq_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.BrakingwithRegenerative.sf_MATLABFunction.RegTq_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_BrakingwithRegenerative_sf_MATLABFunction_RegTq_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.BrakingwithRegenerative.sf_MATLABFunction.RegTq_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_BrakingwithRegenerative_b_sf_MATLABFunction_RegTq_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.BrakingwithRegenerative_b.sf_MATLABFunction.RegTq_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_BrakingwithRegenerative_b_sf_MATLABFunction_RegTq_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.BrakingwithRegenerative_b.sf_MATLABFunction.RegTq_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Compare_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Compare, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Compare_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Compare_d, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Compare_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Compare_g, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant14_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant14, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_a, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_h, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant1_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant1_l, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2_n, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2_p, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant2_pf_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant2_pf, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_f, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_it_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_it, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_n, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant3_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant3_o, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant4_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant4, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant4_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant4_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant7_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant7, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant8_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant8, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_a, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_aq_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_aq, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_bb_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_bb, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_bc_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_bc, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_dd_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_dd, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_do_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_do, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_du_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_du, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_dw_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_dw, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_f, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_g, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_j3_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_j3, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_jv_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_jv, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_kc_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_kc, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_mf_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_mf, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_mu_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_mu, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_n, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_o, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_o4_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_o4, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_ob_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_ob, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Constant_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Constant_p, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Divide_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Divide, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Divide1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Divide1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Divide_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Divide_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Enabled_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Enabled_a, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Gain, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_GearRatio_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.GearRatio, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_LogicalOperator_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.LogicalOperator, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_LogicalOperator1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.LogicalOperator1, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MaxTqpermotorNm_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MaxTqpermotorNm, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Max_Power_chargekW_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Max_Power_chargekW, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Max_Power_dischargekW_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Max_Power_dischargekW, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Max_Tq_per_motor_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Max_Tq_per_motor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MaximumTorqueperengineNm_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MaximumTorqueperengineNm, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MaximumTransmissionTorqueDynami_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MaximumTransmissionTorqueDynami, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MaximumTransmissionTorqueStatic_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MaximumTransmissionTorqueStatic, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_a, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_a0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_a0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_l, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_n, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_p, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge1_pg_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge1_pg, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2_j, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2_l, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_lx_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2_lx, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge2_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge2_o, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge3_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge3, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge3_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge3_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge3_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge3_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge4_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge4, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge5_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge5, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge5_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge5_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge6_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge6, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge7_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge7, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MergeTq_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MergeTq_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_MergeTq_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.MergeTq_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_c, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_d, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_g, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_j, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_kj_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_kj, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_kt_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_kt, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_l, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_li_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_li, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Merge_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Merge_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_OutportBufferForFlag_Power_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.OutportBufferForFlag_Power, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_OutportBufferForFlags_num5_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_B.OutportBufferForFlags_num5, sizeof(double), (uint32)4, (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Product_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Product, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_RT_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.RT_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_RT_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.RT_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Saturation_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Saturation, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Saturation_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Saturation_f, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Saturation_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Saturation_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Saturation_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Saturation_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_SteeringWheelMaximumAngle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.SteeringWheelMaximumAngle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_SteeringWheelMaximumAngle_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.SteeringWheelMaximumAngle_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_SteeringWheelMaximumAngle_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.SteeringWheelMaximumAngle_p, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_SteeringWheelSaturationpersited_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.SteeringWheelSaturationpersited, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Steering_Ratio_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Steering_Ratio, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Subtract_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Subtract, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_TowheelTqdynamic_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.TowheelTqdynamic, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_TowheelTqstatic_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.TowheelTqstatic, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Tq_diff_Max_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Tq_diff_Max, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Tq_diff_maxNm_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Tq_diff_maxNm, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Tq_max_motorNm_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Tq_max_motorNm, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_TransmisionRatio_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.TransmisionRatio, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Wheelbasem_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Wheelbasem, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Yaw_Inertiakgm3_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Yaw_Inertiakgm3, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_Zero_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.Zero, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_approx2095_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.approx2095, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_approx2095_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.approx2095_h, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_exptcycletau1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.exptcycletau1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_initial_limitation_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.initial_limitation, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_initial_limitation_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.initial_limitation_m, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_Acceleratorbehaviour_throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_Acceleratorbehaviour.throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_Acceleratorbehaviour_b_throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_Acceleratorbehaviour_b.throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_Acceleratorbehaviour_br_throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_Acceleratorbehaviour_br.throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_Acceleratorbehaviour_o_throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_Acceleratorbehaviour_o.throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_b_CKF_act0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_b.CKF_act0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_f_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_f.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_g_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_g.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_gm_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_gm.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_h_RegTq_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_h.RegTq_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_h_RegTq_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_h.RegTq_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_m_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_m.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_mk_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_mk.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction1_ny_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction1_ny.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction2_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction2.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction2_b_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction2_b.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction2_e_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction2_e.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction2_l_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction2_l.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction2_m_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction2_m.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_a_CKF_act0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_a.CKF_act0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_ab_RPM_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_ab.RPM, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_d_value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_d.value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_e_SKF_act0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_e.SKF_act0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_fa_RPM_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_fa.RPM, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_fq_SKF_act0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_fq.SKF_act0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_i1_CKF_act1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_i1.CKF_act1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_k2_CKF_act0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_k2.CKF_act0, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_mt_CKF_act1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_mt.CKF_act1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_sf_MATLABFunction_n_RPM_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.sf_MATLABFunction_n.RPM, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_u602pi_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.u602pi, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_u602pi_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.u602pi_e, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_udifference_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.udifference, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_B_udifference1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_B.udifference1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_A_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.A, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_AA_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.AA, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_A_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.A_b, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_A_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.A_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_B_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.B, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_B_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.B_i, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_B_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.B_k, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_Previous_IN_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.Previous_IN, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_DW_Previous_OUT_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_DW.Previous_OUT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_P_ANm_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.ANm_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_ANm_Gain_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.ANm_Gain_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Accu_Temperature_Limitation_Fla_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Accu_Temperature_Limitation_Fla, sizeof(char), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_CKF_act_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.CKF_act_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_CKF_act_Y0_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.CKF_act_Y0_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_CompareToConstant1_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.CompareToConstant1_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_CompareToConstant_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.CompareToConstant_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_CompareToConstant_const_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.CompareToConstant_const_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant14_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant14_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_ab_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_ab, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_fp_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_fp, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_ln_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_ln, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant1_Value_p2_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant1_Value_p2, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_g1_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_g1, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_hv_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_hv, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant2_Value_mw_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant2_Value_mw, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant3_Value_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant3_Value_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant4_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant4_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant4_Value_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant4_Value_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant5_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant5_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant6_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant6_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant6_Value_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant6_Value_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant7_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant7_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant8_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant8_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_ad_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_ad, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_ae_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_ae, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_dl_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_dl, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_dm_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_dm, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_f0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_f0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_ib_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_ib, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_k4_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_k4, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Constant_Value_n5_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Constant_Value_n5, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Cornering_Stiffness_FN_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Cornering_Stiffness_FN_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Cornering_Stiffness_RN_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Cornering_Stiffness_RN_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory10_InitialValue_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory10_InitialValue, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory1_InitialValu_fl_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory1_InitialValu_fl, sizeof(char), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory1_InitialValue_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory1_InitialValue, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory1_InitialValue_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory1_InitialValue_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory1_InitialValue_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory1_InitialValue_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory1_InitialValue_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory1_InitialValue_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory_InitialValue_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory_InitialValue, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory_InitialValue_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory_InitialValue_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DataStoreMemory_InitialValue_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DataStoreMemory_InitialValue_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DiametertoRadius_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DiametertoRadius_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_DiametertoRadius_Gain_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.DiametertoRadius_Gain_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_EffectiveRollingDiameterinch_Va_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.EffectiveRollingDiameterinch_Va, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_EffectiveRollingDiameterinch__b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.EffectiveRollingDiameterinch__b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Enabled_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Enabled_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Accu_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Accu_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Accu_const_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Accu_const_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Inv_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Inv_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Inv_const_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Inv_const_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Mot_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Mot_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flag_Mot_const_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flag_Mot_const_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Flags_num5_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Flags_num5_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Fy_RN0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Fy_RN0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Fyperwheel_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Fyperwheel_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Fyperwheel_Gain_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Fyperwheel_Gain_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain1_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain1_Gain_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain1_Gain_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain1_Gain_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain1_Gain_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain5_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain5_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain5_Gain_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain5_Gain_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain6_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain6_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain6_Gain_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain6_Gain_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_co_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_co, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_cv_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_cv, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gain_Gain_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gain_Gain_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_GearRatio_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.GearRatio_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gravity1_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gravity1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gravity1_Gain_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gravity1_Gain_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Gravity_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Gravity_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Handlinginfinf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Handlinginfinf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Integrator_IC_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Integrator_IC, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Inverters_Temperature_Limitatio_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Inverters_Temperature_Limitatio, sizeof(char), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_chg_bp01Data_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_chg_bp01Data, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_chg_bp01Data_b_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_chg_bp01Data_b, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_chg_tableData_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_chg_tableData, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_chg_tableData_p_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_chg_tableData_p, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_dischg_bp01Dat_m_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_dischg_bp01Dat_m, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_dischg_bp01Data_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_dischg_bp01Data, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_dischg_tableDa_g_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_dischg_tableDa_g, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_SoC_SoP_dischg_tableData_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_SoC_SoP_dischg_tableData, sizeof(double), (uint32)8, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_Temp_SoP_chg_bp01Data_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_Temp_SoP_chg_bp01Data, sizeof(double), (uint32)5, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_Temp_SoP_chg_bp01Data_i_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_Temp_SoP_chg_bp01Data_i, sizeof(double), (uint32)5, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_Temp_SoP_chg_tableData_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_Temp_SoP_chg_tableData, sizeof(double), (uint32)5, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Lookup_Temp_SoP_chg_tableData_m_Ptr = initInstance_vectorWrapper((uint32)&Torque_Control_P.Lookup_Temp_SoP_chg_tableData_m, sizeof(double), (uint32)5, (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Masskg0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Masskg0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxFx_RLN0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxFx_RLN0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxFx_RRN0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxFx_RRN0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxTq_RLNm0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxTq_RLNm0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxTq_RLNm0inf_Y0_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxTq_RLNm0inf_Y0_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxTq_RRNm0inf_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxTq_RRNm0inf_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxTq_RRNm0inf_Y0_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxTq_RRNm0inf_Y0_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaxTqpermotorNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaxTqpermotorNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Max_Power_chargekW_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Max_Power_chargekW_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Max_Power_dischargekW_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Max_Power_dischargekW_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Max_Tq_per_motor_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Max_Tq_per_motor_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTorqueperengineNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTorqueperengineNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTorquepermotorNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTorquepermotorNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTransmissionTorqueDyna_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTransmissionTorqueDyna_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTransmissionTorqueDynami_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTransmissionTorqueDynami, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTransmissionTorqueStat_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTransmissionTorqueStat_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MaximumTransmissionTorqueStatic_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MaximumTransmissionTorqueStatic, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge1_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge1_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge1_InitialOutput_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge1_InitialOutput_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge1_InitialOutput_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge1_InitialOutput_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge2_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge2_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge2_InitialOutput_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge2_InitialOutput_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge3_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge3_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge3_InitialOutput_n_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge3_InitialOutput_n, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge4_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge4_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge5_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge5_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge6_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge6_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge7_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge7_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MergeTq_RL_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MergeTq_RL_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_MergeTq_RR_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.MergeTq_RR_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Merge_InitialOutput_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Merge_InitialOutput_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Motors_Temperature_Limitation_F_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Motors_Temperature_Limitation_F, sizeof(char), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Out1_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Out1_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Out_Throttle_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Out_Throttle_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Out_Throttle_Y0_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Out_Throttle_Y0_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_RT_L_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.RT_L_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_RT_R_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.RT_R_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Rear_Trackwidthm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Rear_Trackwidthm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SKF_act_Y0_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SKF_act_Y0, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SKF_act_Y0_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SKF_act_Y0_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_ko_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_ko, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_lw_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_lw, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_LowerSat_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_LowerSat_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_is_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_is, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation1_UpperSat_m_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation1_UpperSat_m, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_ey_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_ey, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_f3_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_f3, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_fi_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_fi, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_LowerSat_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_LowerSat_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_fg_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_fg, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Saturation_UpperSat_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Saturation_UpperSat_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SteeringWheelMaximumAngle_Val_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SteeringWheelMaximumAngle_Val_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SteeringWheelMaximumAngle_Val_o_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SteeringWheelMaximumAngle_Val_o, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SteeringWheelMaximumAngle_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SteeringWheelMaximumAngle_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_SteeringWheelSaturationpersited_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.SteeringWheelSaturationpersited, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Steering_Ratio_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Steering_Ratio_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_h_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_h, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch1_Threshold_p_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch1_Threshold_p, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_a_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_a, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_b_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_b, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_d_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_d, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_e_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_e, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_f_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_f, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Switch_Threshold_i_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Switch_Threshold_i, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan110_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan110_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan110_const_c_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan110_const_c, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan50_const_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan50_const, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan50_const_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan50_const_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan50_const_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan50_const_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Temphigherthan50_const_l_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Temphigherthan50_const_l, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TomotorTqRT_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TomotorTqRT_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Torque_RLNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Torque_RLNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Torque_RRNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Torque_RRNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Tq_diff_Max_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Tq_diff_Max_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Tq_diff_maxNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Tq_diff_maxNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Tq_max_motorNm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Tq_max_motorNm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TransmisionRatio_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TransmisionRatio_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TransmisionRatio_Value_j_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TransmisionRatio_Value_j, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TransmissionGearRatio_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TransmissionGearRatio_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TransmissionRatio1_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TransmissionRatio1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_TransmissionRatio_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.TransmissionRatio_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Wheelbasem_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Wheelbasem_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Yaw_Inertiakgm3_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Yaw_Inertiakgm3_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_Zero_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.Zero_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_ct_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.ct_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_exptcycletau1_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.exptcycletau1_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_halfrange_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.halfrange_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_inchtom1_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.inchtom1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_inchtom_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.inchtom_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_initial_limitation_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.initial_limitation_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_initial_limitation_Value_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.initial_limitation_Value_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_range_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.range_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_rpm_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.rpm_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_rpm_Value_k_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.rpm_Value_k, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_u602pi_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.u602pi_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_u602pi_Gain_g_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.u602pi_Gain_g, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_udifference1_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.udifference1_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_udifference_Gain_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.udifference_Gain, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_P_zero_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_P.zero_Value, sizeof(double), (uint32)ASD_PARAMETER);
    self->RTWWrapper_Torque_Control_U_ACCEL_F_X_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_F_X_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ACCEL_F_Y_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_F_Y_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ACCEL_F_Z_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_F_Z_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ACCEL_R_X_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_R_X_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ACCEL_R_Y_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_R_Y_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ACCEL_R_Z_SI_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ACCEL_R_Z_SI, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_APPS1_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.APPS1_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_APPS2_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.APPS2_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Accumulator_Current_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Accumulator_Current, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Accumulator_Voltage_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Accumulator_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_BrakeSensor_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.BrakeSensor_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Car_State_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Car_State, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_CriticalDisconnection_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.CriticalDisconnection, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Gyro_F_Z_Deg_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Gyro_F_Z_Deg, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Highest_CellTemp_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Highest_CellTemp, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_RL_rads_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.RL_rads, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_RR_rads_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.RR_rads, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_ShutdownClosed_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.ShutdownClosed, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_SoC_High_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.SoC_High, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_SoC_Low_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.SoC_Low, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_SteeringSensor_Bits_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.SteeringSensor_Bits, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Susp_F_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Susp_F_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Susp_F_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Susp_F_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Susp_R_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Susp_R_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Susp_R_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Susp_R_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_TV_Mode_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.TV_Mode, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Temp_IGBT_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Temp_IGBT, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Temp_Motors_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Temp_Motors, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_TorqueEnable_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.TorqueEnable, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Apps_Sat_Down_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Apps_Sat_Down, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Apps_Sat_Up_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Apps_Sat_Up, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_CKF_Initial_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_CKF_Initial, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Cte_CKF_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Cte_CKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Cte_SKF_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Cte_SKF, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_K_Reduction_P_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_K_Reduction_P, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_K_Reduction_Temperature_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_K_Reduction_Temperature, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Max_Regenerative_Torque_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Max_Regenerative_Torque, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_Power_Limit_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_Power_Limit, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_VDC_SKF_Initial_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.VDC_SKF_Initial, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Vel_RL_kmh_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Vel_RL_kmh, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Vel_RR_kmh_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Vel_RR_kmh, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_U_Workshop_Mode_Enable_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_U.Workshop_Mode_Enable, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_APPS_Implausibility_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.APPS_Implausibility, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Brake_Implausibility_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Brake_Implausibility, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_CKF_actual_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.CKF_actual, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Dash_Speed_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Dash_Speed, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Fy_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Fy_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Handling_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Handling, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Mass_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Mass, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Max_Fx_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Max_Fx_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Max_Fx_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Max_Fx_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Max_Torque_RL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Max_Torque_RL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Max_Torque_RR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Max_Torque_RR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_MeasVDCTorque_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.MeasVDCTorque_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_MeasVDCTorque_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.MeasVDCTorque_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Power_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Power, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_PowerLimitReached_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.PowerLimitReached, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_PowerMean500ms_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.PowerMean500ms, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Pumps_Control_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Pumps_Control, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Regenerative_Enable_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Regenerative_Enable, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_SKF_actual_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.SKF_actual, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_SteeringSensor_Value_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.SteeringSensor_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_TV_Flag_CarBehaviour_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.TV_Flag_CarBehaviour, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_TV_Flag_Power_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.TV_Flag_Power, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_TV_Flag_Temperature_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.TV_Flag_Temperature, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_TV_Flag_WheelSpinRL_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.TV_Flag_WheelSpinRL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_TV_Flag_WheelSpinRR_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.TV_Flag_WheelSpinRR, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Throttle_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Throttle, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Torque_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Torque_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Torque_OK_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Torque_OK, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Torque_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Torque_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Torque_RLwc_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Torque_RLwc, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_Torque_RRwc_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.Torque_RRwc, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_current_L_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.current_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_Torque_Control_Y_current_R_Ptr = initInstance_scalarWrapper((uint32)&Torque_Control_Y.current_R, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_Torque_Control(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_Torque_Control_ClassMethodList =
{
    (MethodPtr)_L1_getPid_Torque_Control
};
/* Definition of the class header */
static ASDClassHeader RTWTop_Torque_Control_ClassHeader =
    {0, 1, 0, 530 + 0, (MethodList *)0, (MethodList *)&RTWTop_Torque_Control_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_Torque_Control_Class RTWTop_Torque_Control_ClassObj = {{1, {&RTWTop_Torque_Control_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_Torque_Control_Obj *initInstance_RTWTop_Torque_Control(void)
{
    struct RTWTop_Torque_Control_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_Torque_Control);
    return self;
}
void setDeltaT_Torque_Control(void)
{
}
