/*****************************************************************************
 *
 * vdc_r2022a_instances.c
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
  /* use void* as instance tree wrapper object pointer type */
 #define Y_PRIMIT_VOID_PTR_FOR_ADDR
#define bool RTW_bool
#include "vdc_r2022a.h"
#include "vdc_r2022a_private.h"
#undef bool
#undef false
#undef true
#include "../a_basdef.h"
#include "vdc_r2022a_instances.h"
extern    B_vdc_r2022a_T vdc_r2022a_B;
extern    DW_vdc_r2022a_T vdc_r2022a_DW;
extern    ExtU_vdc_r2022a_T vdc_r2022a_U;
extern    ExtY_vdc_r2022a_T vdc_r2022a_Y;
/* Initialization of Simulink model */
struct RTWTop_vdc_r2022a_Obj *initModel_RTWTop_vdc_r2022a(void)
{
    struct RTWTop_vdc_r2022a_Obj *model;
    /* Level 1 class initialization */
    initClass_RTWTop_vdc_r2022a (&RTWTop_vdc_r2022a_ClassObj);
    /* Level 1 object instantiation */
    model = initInstance_RTWTop_vdc_r2022a();
    return(model);
}
/* Class initialization */
void initClass_RTWTop_vdc_r2022a(struct RTWTop_vdc_r2022a_Class *self)
{
    /* Level 1 class variables */
    self->RTWWrapper_vdc_r2022a_B_Merge1_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_B.Merge1, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_B_Merge2_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_B.Merge2, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_B_Merge3_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_B.Merge3, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_DW_A_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_DW.A, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_DW_ERROR_Counter_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_DW.ERROR_Counter, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_APPS1_Value_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.APPS1_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_APPS2_Value_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.APPS2_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Accumulator_Current_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Accumulator_Current, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Accumulator_Voltage_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Accumulator_Voltage, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_BrakeSensor_Value_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.BrakeSensor_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Car_State_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Car_State, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_CriticalDisconnection_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.CriticalDisconnection, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_RL_Vel_ms_Wheel_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.RL_Vel_ms_Wheel, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_RL_rads_Motor_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.RL_rads_Motor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_RR_Vel_ms_Wheel_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.RR_Vel_ms_Wheel, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_RR_rads_Motor_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.RR_rads_Motor, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Shutdown_PackageIntck_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Shutdown_PackageIntck, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_SteeringSensor_Value_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.SteeringSensor_Value, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Susp_F_L_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Susp_F_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Susp_F_R_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Susp_F_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Susp_R_L_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Susp_R_L, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Susp_R_R_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Susp_R_R, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_TV_Mode_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.TV_Mode, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_TorqueEnable_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.TorqueEnable, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_VDC_Max_tire_slip_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.VDC_Max_tire_slip, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_Workshop_Mode_Enable_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.Workshop_Mode_Enable, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_ACCEL_X_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_ACCEL_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_ACCEL_Y_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_ACCEL_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_ACCEL_Z_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_ACCEL_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_GYRO_X_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_GYRO_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_GYRO_Y_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_GYRO_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_GYRO_Z_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_GYRO_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_PITCH_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_PITCH, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_ROLL_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_ROLL, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_Vel_X_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_Vel_X, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_Vel_Y_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_Vel_Y, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_Vel_Z_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_Vel_Z, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_U_el_YAW_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_U.el_YAW, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_APPS_Implausibility_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.APPS_Implausibility, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_Power_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.Power, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_PowerLimitReached_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.PowerLimitReached, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_PowerMean500ms_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.PowerMean500ms, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_TC_WARNING_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.TC_WARNING, sizeof(char), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_Torque_L_out_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.Torque_L_out, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_Torque_OK_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.Torque_OK, sizeof(double), (uint32)ASD_VARIABLE);
    self->RTWWrapper_vdc_r2022a_Y_Torque_R_out_Ptr = initInstance_scalarWrapper((void*)&vdc_r2022a_Y.Torque_R_out, sizeof(double), (uint32)ASD_VARIABLE);
    return;
}
static uint8 * _L1_getPid_vdc_r2022a(ASDObjectPtr self, uint8 *buffer)
{
    uint8 definedFlg = true;
    uint32 programIdentifier = 0;
    if(definedFlg == true)
    {
        addScalar(buffer, (uint8*)&programIdentifier, sizeof(programIdentifier));
    }
    addScalar(buffer, (uint8*)&definedFlg, sizeof(definedFlg));
    return(buffer);
}
/* Class method list */
static MethodList RTWTop_vdc_r2022a_ClassMethodList =
{
    (MethodPtr)_L1_getPid_vdc_r2022a
};
/* Definition of the class header */
static ASDClassHeader RTWTop_vdc_r2022a_ClassHeader =
    {0, 1, 0, 46 + 0, (MethodList *)0, (MethodList *)&RTWTop_vdc_r2022a_ClassMethodList};
/* Definition and initialization of the class object */
struct RTWTop_vdc_r2022a_Class RTWTop_vdc_r2022a_ClassObj = {{1, {&RTWTop_vdc_r2022a_ClassHeader}, {0}}
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,NULL
};
/* Object instantiation */
struct RTWTop_vdc_r2022a_Obj *initInstance_RTWTop_vdc_r2022a(void)
{
    struct RTWTop_vdc_r2022a_Obj *self;
    /* Object instantiation / Implicit memory allocation */
    CREATE_OBJECT(self, RTWTop_vdc_r2022a);
    return self;
}
void setDeltaT_vdc_r2022a(void)
{
}
