/*****************************************************************************
 *
 * Racing_Mode_ETR07_instances.h
 *
 * Part of INTECRIO Simulation Interface for Mathworks Matlab/Simulink
 * Real-Time Workshop and Embedded Coder
 *
 * Generated by INTECRIO Project Integrator, do not edit!
 *
 * Copyright 2007 ETAS (ETAS GmbH)
 *
 *****************************************************************************/
/* Model initialization function prototype */
extern struct RTWTop_Racing_Mode_ETR07_Obj *initModel_RTWTop_Racing_Mode_ETR07(void);
/* Level 1 class object declaration */
extern struct RTWTop_Racing_Mode_ETR07_Class RTWTop_Racing_Mode_ETR07_ClassObj;
/* Level 1 class initialization function prototype */
extern void initClass_RTWTop_Racing_Mode_ETR07(struct RTWTop_Racing_Mode_ETR07_Class *class);
/* Level 1 object instantiation function prototype */
extern struct RTWTop_Racing_Mode_ETR07_Obj *initInstance_RTWTop_Racing_Mode_ETR07(void);
/* Function prototype for module specific setDeltaT() */
void setDeltaT_Racing_Mode_ETR07(void);
/* Definition of the class structure */
struct RTWTop_Racing_Mode_ETR07_Class
{
    ASDObjectHeader objectHeader;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Apps_Sat_Dwn_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Apps_Sat_Up_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_CKF_Initial_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Cte_CKF_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Cte_SKF_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_K_Reduction_P_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_K_Reduction_Temperature_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Max_Regenerative_Torque_In1_Ptr;
    vectorWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Merge_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_Power_Limit_In1_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_B_SKF_Initial_Gain_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Apps_Sat_DwnSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Apps_Sat_DwnSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Apps_Sat_UpSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Apps_Sat_UpSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Apps_Sat_Dwn_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Apps_Sat_Up_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_CKF_Initial_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Cte_CKF_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Cte_SKF_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_K_Reduction_P_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_K_Reduction_Temperature_Val_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Max_Regenerative_Torque_Val_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_Power_Limit_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CEE_SKF_Initial_Value_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CKF_InitialSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CKF_InitialSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_CompareToConstant_const_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Cte_CKFSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Cte_CKFSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Cte_SKFSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Cte_SKFSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_K_Reduction_PSaturation_LowerSa_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_K_Reduction_PSaturation_UpperSa_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_K_Reduction_TemperatureSatura_m_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_K_Reduction_TemperatureSaturati_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Max_Regenerative_TorqueSatura_o_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Max_Regenerative_TorqueSaturati_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Merge_InitialOutput_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Power_LimitSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_Power_LimitSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_SKF_InitialSaturation_LowerSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_P_SKF_InitialSaturation_UpperSat_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_U_CustomMode_Data_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_U_CustomMode_Identifier_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_U_RacingMode_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Apps_Sat_Down_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Apps_Sat_Up_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_CKF_Initial_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Cte_CKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Cte_SKF_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_K_Reduction_P_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_K_Reduction_Temperature_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Max_Regenerative_Torque_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_Power_Limit_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_VDC_SKF_Initial_Ptr;
    scalarWrapper_Obj *RTWWrapper_Racing_Mode_ETR07_Y_Workshop_Mode_Enable_Ptr;
};
/* Definition of the class object structure */
struct RTWTop_Racing_Mode_ETR07_Obj
{
    ASDObjectHeader objectHeader;
};
