set MATLAB=C:\Program Files\MATLAB\R2017b
@"rtw_build.bat" -f Car_State.mk  MODELLIB=Car_Statelib.lib MODELREF_TARGET_TYPE=NONE ISPROTECTINGMODEL=NOTPROTECTING RELATIVE_PATH_TO_ANCHOR=.. MAT_FILE=0 IRTWaitForStartMsg=0
