set MATLAB=F:\Matlab2017b
@"rtw_build.bat" -f Accel_Data_ETR07.mk  MODELLIB=Accel_Data_ETR07lib.lib MODELREF_TARGET_TYPE=NONE ISPROTECTINGMODEL=NOTPROTECTING RELATIVE_PATH_TO_ANCHOR=.. MAT_FILE=0 IRTWaitForStartMsg=0
